### ISSUE TITLE
cpu/adsp2100/2100ops.c - new bug ported in from bug in MAME code (affects DCS playback quality)

### ISSUE THREAD

**Issue by mjrgh** [vpinball/pinmame#102]
The change to this file in commit 9ed410d, which is labeled as ported from MAME/MESS, adds a new bug, which affects DCS playback quality.

Check out the diff:

https://github.com/vpinball/pinmame/commit/9ed410de2e29d8e473b2ab69712a73b0533e9c3e

The changes are all to the implementation of the ABS (ABSOLUTE VALUE) instruction.  The old version had an explicit CLR_S to clear the AS flag in ASTAT, whereas the new code deletes the CLR_S and substitutes CLR_FLAGS.

The addition of CLR_FLAGS is correct, since the instruction is documented as updating the AC-AN-AV-AZ flags.  But the deletion of CLR_S is a bug, because the documentation also says that ABS must set or clear AS, according to the sign of the source operand.  (See the ADSP 2100 User's Manual, 3rd edition, September 1995, section 15, ABSOLUTE VALUE (ABS) instruction: "AS: Set if the source operand is negative. Cleared otherwise.")  CLR_FLAGS doesn't affect AS, so if AS was set going into the instruction, it'll still be set coming out, even if the operand was positive.

This isn't just a harmless bookkeeping detail - it actually breaks the DCS games in a subtle way!  You can observe the effect of the bug on the DCS games by firing up ST-TNG LX7, going to the test menu, running the sound test, and letting track 1 ("1ST TUNE") run on auto-repeat.  You'll hear a sort of flatulent distortion, which is occurring because that new ABS instruction bug is randomizing about 30% of the DCS frames decoded.  It's actually affecting all of the tracks, but it seems to be more audible in tracks with lots of low bass frequencies, and just causes some annoying popping and crackling on most of the other tracks.

If anyone has been asking why the audio for all of the DCS games has been sucking lately, this is probably the answer.

Solution: Add back the CLR_S that was there before, right after the new CLR_FLAGS.

**Comment by toxieainc** [comment]
Neat find! Will include this. But i fear this may not be the only thing still being wrong with DCS, as the versions before that commit also already had some subtle static noise effects.

**Comment by toxieainc** [comment]
Added, thanks @mjrgh ! Can you please double check?

**Comment by toxieainc** [comment]
Unfortunately, https://github.com/vpinball/pinmame/issues/60 is still there after this fix.
