### ISSUE TITLE
Workflow improvement suggestion

### ISSUE THREAD

**Issue by droscoe** [vpinball/pinmame#116]
Where I work, we have a remote branch we can push to that will kick off an automatic build for testing if a change breaks the build.

in GitHub I believe it is possible to trigger a build on pull request as well.  You could set up a special branch for that.  Any pull request made to the special branch would kick off a build automatically.  The developer can check this to make sure the build is good, before creating a pull request for master.

Another possibility is to trigger the build on pull request to master and automatically reject the pull request if the build fails.  If it succeeds. The pull request will remain for the normal workflow of review/merge by the maintainers.

This would improve the workload of the maintainers and help to avoid broken builds on master.

**Comment by jsm174** [comment]
I think it might be as simple as updating all the workflows:

```
on:
  push:
  pull_request:
```

We already have the `dispatch` set up to only run on `push`, so no issues there.

**Comment by droscoe** [comment]
Thanks @jsm174!  I hope people find this useful.

**Comment by jsm174** [comment]
No problem! TBH, we should have it like this from the start. 😄
