### ISSUE TITLE
Recording and playback

### ISSUE THREAD

**Issue by droscoe** [vpinball/pinmame#119]
The documentation says that VPinMAME supports the MAME ability to record and playback gameplay.  Can anyone tell me how to tell VPX to issue the "-record" argument to turn this on?  Thanks!

**Comment by toxieainc** [comment]
VPinMAME doesn't expose it, so if at all, then only the standalone PinMAME(32) variants (at least AFAIK).

**Comment by droscoe** [comment]
> VPinMAME doesn't expose it, so if at all, then only the standalone PinMAME(32) variants (at least AFAIK).

Sorry.  Maybe I'm misspeaking?  When VPX runs a ROM is it using VPinMAME or PinMAME(32)?   I was using "VPinMAME" as a generic term, but realize that may be a mistake.

**Comment by toxieainc** [comment]
Sure! Thanks..
