### ISSUE TITLE
Motordome Bally

### ISSUE THREAD

**Issue by benderle** [vpinball/pinmame#122]
Key Plunger " NUM ENTER" not work for this Table

**Comment by toxieainc** [comment]
Could you please clarify a bit?

**Comment by benderle** [comment]
Hallo toxieanic, danke für Deine Rückmeldung
betreibe mein VPIN Cab mit einem Keyboardhack (Tastatur USB-Platine und die Keys ausgelesen)
Schon immer ist mein Plunger mit der Taste " Num Enter " verknüpft, alle Tables laufen mit der Config nur der Motordome leider nicht. Eine Änderung im VPX zb. auf Taste J geht, aber nicht NUM Enter.
Grüße benderle

**Comment by toxieainc** [comment]
Hmmm.. As this is specific to this table, i looked into the script and it also looks fine. Could you please contact JPsalas about it (i guess this is his table creation, right?)?

**Comment by benderle** [comment]
jep , thats right JP´s
ok, i test my lucky to him.
BIG THX for your Time !!
Greetings Benderle

**Comment by toxieainc** [comment]
Please report back here if you find the solution/problem.

**Comment by toxieainc** [comment]
Ah, yes, that could make sense that its handled somewhere else. I never fully understood all that interaction between the script files, VPM and VPX on key handling.
