### ISSUE TITLE
Missing macOS ci build?

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#132]
I was looking on how to compile / test pinmame on macOS but could not find any related github actions or instructions.

I know it is possible as vpx standalone is using pinmame and compile on macOS

**Comment by jsm174** [comment]
Vpx standalone uses libpinmame not pinmame. 

The CI here compiles `libpinmame` for all platforms. See [here](https://github.com/vpinball/pinmame/blob/master/.github/workflows/libpinmame.yml) and [here](https://github.com/vpinball/pinmame/actions/workflows/libpinmame.yml).

The CI here also makes a build of `xpinmame` for mac but it requires xquartz. See [here](https://github.com/vpinball/pinmame/blob/master/.github/workflows/xpinmame.yml) and [here](https://github.com/vpinball/pinmame/actions/workflows/xpinmame.yml).
