### ISSUE TITLE
Crash with robot and lotr after last few commits 

### ISSUE THREAD

**Issue by jsm174** [vpinball/pinmame#135]
While working on implementing `PinmameGetMaxSoundCommands` and `PinmameGetNewSoundCommands` in libpinmame, tables like robot and lotr are crashing in libpinmame. 

The last working commit is [bbe86bc](https://github.com/vpinball/pinmame/commit/bbe86bc267af3dc83e504444931ce6a3999c51fd): add support for new SC01 ROM dump.

Using the libpinmame test program, when launching robot, is crashes in `SN76477_mixer_w` and the `sn76477` structs are all null. 

![Screenshot 2023-06-21 at 8 01 08 AM](https://github.com/vpinball/pinmame/assets/1197137/ef8226f4-c5f5-4000-afc9-565cc5919cfd)

lotr seems to be crashing in the `at91_reset`:

![Screenshot 2023-06-21 at 8 03 39 AM](https://github.com/vpinball/pinmame/assets/1197137/2501df2a-e6f9-4c5a-8f68-f7525c9f5ee5)

**Comment by volkenborn** [comment]
Robot is odd because it does not use the 1346 sound at all!?
And even if it did, it would need to run the mZAC1146 driver so the additional SN76477 would be supported.
So I think a clean recompile is needed here as some drivers got obviously confused...

**Comment by volkenborn** [comment]
Oh, hang on, I think I see the problem:
toxie anned anoher sound board variant for the old Votrax SC01 (instead of SC01A): SNDBRD_TYPE(19,2)
Yet he also added an entry in sndbrd.c for it which is only allowed for new main board types, but not for subtypes.
This confuses the order. I'll look into it right now.

**Comment by toxieainc** [comment]
Whoops.. Thanks @volkenborn ! I never did something like this before..

**Comment by volkenborn** [comment]
Yeah, no big deal. I forgot all about it as well, so I didn't notice it right away. :)
Should be fixed now.

**Comment by jsm174** [comment]
Thanks for fixing this!
