### ISSUE TITLE
Unresolved externals when building pinmame with VS2022

### ISSUE THREAD

**Issue by IoTDan** [vpinball/pinmame#136]
The following unresolved externals come up after building with VS2022.

it look like this change may be the issue:

ID	Author	Date	Message
565237da2efec147e594e83c5a648156556db41f	toxie <toxieainc@users.noreply.github.com>	5/18/2023 4:22:15 PM +00:00	enable YMFM as new 2151 sound core

Error	LNK2019	unresolved external symbol ymfm_ym2151_create referenced in function my_YM2151_sh_start	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_destroy referenced in function YM2151_sh_stop	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_reset referenced in function YM2151_sh_reset	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_callback referenced in function timercallback	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_invalidate_caches referenced in function YM2151_sh_reset	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_read referenced in function YM2151_status_port_0_r	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_write referenced in function YM2151_word_0_w	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1	
Error	LNK2019	unresolved external symbol ymfm_ym2151_generate referenced in function YM2151UpdateYMFM	PinMAME	C:\Pinball\src\pinmame\2151intf.obj	1

**Comment by orbian** [comment]
I'm seeing this too. With 2017 and 2019 as well.

**Comment by mjrgh** [comment]
You might have to regenerate the project/solution files via CMAKE - I think that’s the definitive build rule set now, and the VS stuff is just there for historical reference and no longer maintained.

**Comment by orbian** [comment]
To get it to work I had to change pinmame.h and change the following defines:
#define HAS_YM2151_NUKED 1
//#define HAS_YM2151_YMFM 1

My build works now. Not sure what ym2151 is but my Bally machine doesn't seem to need it.

**Comment by orbian** [comment]
Running:
win_build PRJ:VPINMAME GEN:10 

built a working VS2019 solution. Tried VS2022 but it wouldn't generate. I might be missing some dependencies.

**Comment by mjrgh** [comment]
> Not sure what ym2151

It's an FM synthesizer chip used in many of the 80s-90s sound boards.  PinMame has (I think) three different implementations now; those HAS_YM2151_xxx macros select which one to use.  The reason for the missing symbols when building against the old .sln is that the latest YM2151 implementation was added recently, after .sln maintenance ceased, so the new files weren't added to the project directly.  Changing the macro to select one of the older implementations will fix the build errors but will get you an out-of-date configuration - the shiny new YM emulator is (presumably) better than the old ones, and at any rate will be the only one that's maintained going forward. 

> Tried VS2022 but it wouldn't generate

It might be worthwhile filing a separate issue about that, in case that's something that needs fixing.  I think the cmake builds are still a little squirrely.

**Comment by droscoe** [comment]
Not sure if this is still an issue or not.  Using the win_build.bat script should make your build pretty bulletproof.  I would not recommend using the versioned SLN files.  I never successfully got those to work.  In general its a bad idea to version project files, through, especially Visual Studio.  With makefiles, its hard to ensure that all of the dependencies from an individual's environment are captured in the versioned file.  Additionally, paths become problematic if, for some reason, relative paths aren't used throughout.  For Visual Studio, there is actually binary code embedded in the project files, which is specific to the user environment it was created in.  Tools like CMake exist to address these problems, and a lot more.  The VPinMAME repository already uses CMake for its CI builds, so its no significant effort to re-purpose them for user builds.  The win_build.bat script makes it a very simple process for Windows builds.

At some point, I'll create a script to generate the non-windows makefil;es too.  I've already addressed the VS2022 issue.  The win_build.bat script lists all of the supported generators from CMake 3.26.  If you are running an earlier version, that generator may not be supported.

**Comment by orbian** [comment]
> Not sure if this is still an issue or not. Using the win_build.bat script should make your build pretty bulletproof. > 

win_build.bat solved the issue. I had to update to the latest cmake to get the VS2022 files to generate.

**Comment by toxieainc** [comment]
Thanks for verifying, closing then. Otherwise @IoTDan please reopen if necessary.
