### ISSUE TITLE
CMake can't generate VS2022 builds

### ISSUE THREAD

**Issue by orbian** [vpinball/pinmame#138]
Using win_build to generate VS2022 build fails with "CMake Error: Could not create named generator Visual Studio 17 2022"

Generating Vs2019 works fine though.

> win_build PRJ:VPINMAME GEN:11

--- GLOBAL VARIABLES ---
PROJECT        : VPINMAME
SAMCOLOR       : YES
PLATFORM       : Win32
GENERATOR      : "Visual Studio 17 2022"
BUILD          : YES
CONFIG         : DEBUG
GEN_INSTVPM    : ""
GEN_LIBPINMAME : ""
GEN_PINMAME    : ""
GEN_PINMAME32  : ""
GEN_VPINMAME   : YES
        1 file(s) copied.
CMake Error: Could not create named generator Visual Studio 17 2022

**Comment by droscoe** [comment]
The ability to generate a particular version of an IDE project depends on the version of CMake you have installed.  What version are you running?

**Comment by orbian** [comment]
I'm using CMake 3.18.3

> The ability to generate a particular version of an IDE project depends on the version of CMake you have installed. What version are you running? Also, do you have VS 2022 installed?

**Comment by droscoe** [comment]
Cmake 3.18.3 supports the following Visual Studio generators:
```
"Visual Studio 6"
"Visual Studio 7"
"Visual Studio 7 .NET 2003"
"Visual Studio 8 2005"
"Visual Studio 9 2008"
"Visual Studio 10 2010"
"Visual Studio 11 2012"
"Visual Studio 12 2013"
"Visual Studio 14 2015"
"Visual Studio 15 2017"
"Visual Studio 16 2019"
```
CMake 3.18.4 was released on October 20, 2020.  Visual Studio 19 2022 is not support by your version of cmake, which is why it doesnt work.

**Comment by toxieainc** [comment]
Will close then.
