### ISSUE TITLE
Volume issues with altsound

### ISSUE THREAD

**Issue by Crrispy** [vpinball/pinmame#141]
Hello, I've upgraded to latest 1348 VPX 10.8 build and Vpinmame 3.6 480 before posting this, no change. I'm not sure if the issue is related to VPX or Vpinmame, but since altsound is managed by pinmame, I suppose the issue should be mentioned here.
Maybe it's related to #113 too.
I'm using altsound for White Water. Background music is too loud. I can adjust/lower the volume using the normal wpc volume buttons, but then as soon as a sound is triggered, the volume of the music goes back all the way up. 
Then, when the ball is lost and a new ball launched in the shooter lane, it's back to the correct volume. But again, as soon as the ball is launched (which triggers a sound), the music goes up way too loud and remains loud until the next ball is launched. 
I also have issue with LOTR altsound, but different. The music volume can also be adjusted with the table volume control, but there, when some sounds are played, the music also goes up too loud, but not permanently as on White Water, just during the time the sound is played, then it's back to normal. But this also makes the altsound unusable, very annoying.
Note: I have no volume control apps installed, just VPX, Vpinmame, B2S server.
Thanks.

**Comment by Crrispy** [comment]
> It might be related, but also might not be the altsound at all. First thing I would suggest is running without the altsound. Make sure the problem isn’t with the table sound. If the table sounds are loud, you should adjust them before trying to use the altsound. If table sounds are good and the issue only pops up with the altsound, then that’s probably it. What’s strange is that the issue with altsound is that they are too quiet, not too loud. Finally, there are a lot of layered sounds on a vpin table. You really should consider using a volume manager

Original sound has no issue, as all other WPC tables I have installed without altsound yet. I will try another one tomorrow.

**Comment by droscoe** [comment]
@Crrispy if you are on discord, send me a message @mrgrynch

**Comment by Crrispy** [comment]
> @Crrispy if you are on discord, send me a message @mrgrynch

I don't have Discord, well not yet. Today I tried with STTNG and its "ultimate" altsound, and I don't have the issue. It's still definitely there with White Water. Is the altsound code different for DCS and pre-DCS machines? I'm going to try a couple of others to try to isolate the issue.

**Comment by droscoe** [comment]
Shoot me an email then: twistgrav@yahoo.com.  There's something I'd like you to try

**Comment by droscoe** [comment]
@Crrispy can you confirm that my changes re: #113 resolved this problem for you?  If so, then @toxieainc , this can probably be closed and left with 113

**Comment by Crrispy** [comment]
Hello, I confirm that the latest DLLs you sent me on the 13th solved all
altsounds problems for me, everything is working fine now.

Le mer. 16 août 2023 à 19:19, Dave Roscoe ***@***.***> a
écrit :

**Comment by droscoe** [comment]
@toxieainc this can be closed with PR 142 merged

**Comment by toxieainc** [comment]
👍
