### ISSUE TITLE
Virus in PinMAME-sc-3.6-573-5d6459d-win-x86.zip?

### ISSUE THREAD

**Issue by LunatechFringe** [vpinball/pinmame#148]
I attempted to download PinMAME-sc-3.6-573-5d6459d-win-x86.zip today via Chrome on Windows 11.  It reportedly contained Program:Win32/Wacapew.C!ml.  All other files downloaded without any issues.  Also, the previous beta version of this file downloaded without any issues.

**Comment by toxieainc** [comment]
Unfortunately we still get a lot of false positives with virus scanners, also e.g. with windows defender.  :/

**Comment by LunatechFringe** [comment]
For what it's worth, Chrome / Windows 11 blocked the download.  That's unfortunate, but I understand I only need VPinMAME files for Visual Pinball.  I'll go ahead and close this request.  Thanks for the quick response!
