### ISSUE TITLE
Unknown AltSound CSV Format

### ISSUE THREAD

**Issue by droscoe** [vpinball/pinmame#151]
I came across the AltSound for Red & Ted's Road Show.  It has a CSV format that's not the usual format:

`ID,CHANNEL,DUCK,GAIN,LOOP,STOP,NAME,FNAME,GROUP,SHAKER,SERIAL,PRELOAD,STOPCMD`

First, one of the samples had a channel assignment of '2' which is normally not allowed.  Second, there are several additional columns which I am not familiar with: "GROUP", "SHAKER", "SERIAL", "PRELOAD", "STOPCMD".  Where does this format come from?  Thanks!

**Comment by toxieainc** [comment]
No clue.. Maybe contacting the author could help?

**Comment by mjrgh** [comment]
I have a wild guess, not based on anything I know about that CSV file, just what I've read about the commercial after-market replacement sound boards: at least one of those products includes an option for a shaker motor that you can trigger via sound commands.  Based on the presence of the SHAKER column, my wild guess is that this file was created for use with one of those boards (or copy-and-pasted from one that was).

**Comment by droscoe** [comment]
> I have a wild guess, not based on anything I know about that CSV file, just what I've read about the commercial after-market replacement sound boards: at least one of those products includes an option for a shaker motor that you can trigger via sound commands. Based on the presence of the SHAKER column, my wild guess is that this file was created for use with one of those boards (or copy-and-pasted from one that was).

Why means they are using PinMAME in commercial product somewhere?  Ok, I'm not going to worry about it then.  The original AltSound code didn't care about what channel number was actually used in the CSV.  It would just ignore anything that was not 0, 1 or -1/undefined.  In the new code, I am rejected anything that is not one of these, so having a channel value of 2 is causing the parser to quit with an error, so the package no longer works.  Technically this is a regression, so I'm wondering if I should allow parsing to continue but ignore it like the original code.  @toxieainc what would be your preference?

**Comment by droscoe** [comment]
@toxieainc I ended up allowing unknown channels through, at least for traditional altsounds, just like the original.  G-Sound format can afford to be stricter because it doesn't to be backward compatible with anything else.  I think this one can be closed
