### ISSUE TITLE
ROMs with mono audio output to send to both L/R channels so it works on SSF  (like Medieval Madness)

### ISSUE THREAD

**Issue by Ltek** [vpinball/pinmame#155]
I wasted 6 hrs testing everything I know only to find out that the ROMs all have only mono audio output. It will not work in SSF

Please fix this in vpinmame so we dont need to do hacks (and waste tons of time not knowing this is the problem since its not documented with the ROMs!)

**Comment by droscoe** [comment]
This is a very common problem and there are several ways to solve it.  One is to look at your sound card settings.  Some let you send center channel to L/R, others activate a “phantom” center channel that does the same thing.  If your sound card does not support this you can use EQAPO to copy the center channel to your L/R speakers.

**Comment by Ltek** [comment]
IMO users should be challenged while playing the table... not setting up the software to run the table. The apps (collectively) are too difficult to setup. Table audio is one area with a lot of inconsistencies but audio can be addressed easier than most other config issues. 

Ideally, no audio would ever run from the ROM. It would be all AltSound -- auto extracted and normalized (sound levels) by VPM. Dealing with greatly varying sound level are a serious PITA (which is why PinVol is basically a defacto requirement) and could be automated using libraries which have existed since WinAmp days. I have not done any real code for 25 yrs so I'm not the guy to try doing it these days but I'd imagine things are easier now than they were back then.

I did try EQAPO and it doesnt seem to work for that, not sure why. I installed it to use with PinVol so I know the app is working but no clue why it will not copy C to L/R. I tried a few times , then gave. Luckily a few google searches and I found a site that posted the AltSound for mm_109 (not the C version) so I'm using it.

**Comment by toxieainc** [comment]
> Ideally, no audio would ever run from the ROM. It would be all AltSound -- auto extracted and normalized (sound levels) by VPM. Existing code could have been integrated and automated 2-3 years ago... https://sourceforge.net/p/pinmame/code/5079/

This is not the point of the PinMAME project. PinMAME's main focus is preserving old pinball machines via as-accurate-as-possible emulation.
Everything else (like Altsound) is just the cherry on top for endusers.

Also note that Altsound cannot mimic the original sound in all its accuracy. Why? Altsound just captures sound commands that are emitted from the CPU emulation, that are then 'translated' into some interpretation of them and handed over to a sample playing library (BASS at the moment) with some bells and whistles to tweak the sample playback accordingly.
But some soundboards/interfaces of some machines (especially the older ones) do not just playback a sample. They can do various other things that are hidden behind these seemingly simple sound commands.
Older machines do not even emit sound commands in the newskool sense, but are even more complicated and thus could/do not even work via the Altsound interface.

> Greatly varying sound levels are a very difficult to deal with in vPin (thus PinVol is basically a requirement). Normalization could be integrated. Libraries have existed since the '90s (WinAmp days). I have not done any real code for 25 yrs so I'm not the guy to try doing it these days but I'd imagine things are easier now than they were back then.

Normalization is IMHO nothing that anyone should ever require. Its just a modern artifact of stupid things like the loudness war.
So at least PinMAME itself will not add something like this, as it can alter the intention of the original composers dramatically.

Coming back to the original request: So what you'd want is that PinMAME emulation would always output Stereo? This should already be the case, or do you mean the Altsound component?
Which Altsound mode do you use?

**Comment by toxieainc** [comment]
Correction: PinMAME actually really distinguishes between machines that feature stereo (e.g. SAM, Capcom, DE, etc) and those with just mono (e.g. WPC).

**Comment by Ltek** [comment]
> > Ideally, no audio would ever run from the ROM. It would be all AltSound -- auto extracted and normalized (sound levels) by VPM. Existing code could have been integrated and automated 2-3 years ago... https://sourceforge.net/p/pinmame/code/5079/
> 
> This is not the point of the PinMAME project. PinMAME's main focus is preserving old pinball machines via as-accurate-as-possible emulation. Everything else (like Altsound) is just the cherry on top for endusers.
> 
> Also note that Altsound cannot mimic the original sound in all its accuracy. Why? Altsound just captures sound commands that are emitted from the CPU emulation, that are then 'translated' into some interpretation of them and handed over to a sample playing library (BASS at the moment) with some bells and whistles to tweak the sample playback accordingly. But some soundboards/interfaces of some machines (especially the older ones) do not just playback a sample. They can do various other things that are hidden behind these seemingly simple sound commands. Older machines do not even emit sound commands in the newskool sense, but are even more complicated and thus could/do not even work via the Altsound interface.
> 

As an engineer and an audio enthusiast I can say with 100% confidence you can never achieve 'the player hearing an accurate out like the original table'.  You are ignoring that playback hardware has the most influence on the 'sound you hear'. Your goal of reproducing 'accurate to the original' audio is literally impossible unless the playback hardware is identical -- a vPin never be anywhere close since its 1000 "tables" using hardware nowhere like those 1000 original tables. 

The above is the core of why your goal can never be achieved. To round out the conversation you also need to consider the complete journey of the process for audio conversion and the way humans hear sound. A few of the main variables are: 

1. original source content (analog or digital audio from the table's ROM) is always translated into a format that the PC can read. So no matter what the ROM, you are converting the original source, all conversions are an "approximation" (as you put it). Thus, its irrelevant if that is happening 

2. conversion method/process // the hardware and software reading the source content, and converting it
-- current audio conversion methods are so good the final output is so close to the source, any differences are not perceived by any human ear. Thus the conversion method is irrelevant as it imparts no perceivable change in the audio content

3. the playback hardware (DSL, amps, speakers). 
-- discussed this at the start since its the most important factor.

In summary, all recorded audio is "translated into some interpretation" no matter which way it goes analog <-> digital. Then the human ear (which are all different in frequency response and interpretation) translate it again into your brain. Thus, no matter what the source (the original pinball machine itself in the case), you can never have the exactly same final result.

> > Greatly varying sound levels are a very difficult to deal with in vPin (thus PinVol is basically a requirement). Normalization could be integrated. Libraries have existed since the '90s (WinAmp days). I have not done any real code for 25 yrs so I'm not the guy to try doing it these days but I'd imagine things are easier now than they were back then.
> 
> Normalization is IMHO nothing that anyone should ever require. Its just a modern artifact of stupid things like the loudness war. So at least PinMAME itself will not add something like this, as it can alter the intention of the original composers dramatically.

This ask is not how you are interpreting it. Lets change the feature explanation to "Minimum audio level"... thus a User definable minimum volume for all ROM audio output -- which may impart a DB boost if needed. (nothing to do with loudness -- I'm not talking about normalizing 'within' the ROM).   This would be a simple/easy fix for a problem many ROMs have volume is often way to low even at 28-32 volume. I've had to use AltSound for many since balancing the overall vPin's volume levels (table sounds effects, backbox / ROM, etc) even with PinVol its not god enough. 

Using AltSound allows for more fine-tuned control over volume levels. So if PinMAME had the option to auto extract/convert a ROM to AltSound (on first load) it would be easier to set a min volume for all backbox audio output.

 
> Coming back to the original request: So what you'd want is that PinMAME emulation would always output Stereo? This should already be the case, or do you mean the Altsound component? Which Altsound mode do you use?

yes coming back... the problem I ran into is that when a table ROM audio was Mono, when using SSF there was audio silence.  I had to use EQ/APO to copy the Center channel (the Mono channel) to L/R. Since the entire world uses Stereo (not Mono) I was surprised PinMAME does not feed the Mono audio to both L/R channels automatically.
... this is not related to AltSound. I just proposed (as above) AltSound as a single, already widely used, solution to multiple issues (poor ROM volume levels, mono to stereo conversion, etc)

**Comment by toxieainc** [comment]
Unfortunately it seems like you missed my main point: Most machines that PinMAME emulates do not just playback samples one after another that are stored in some form in a ROM. The majority of machines generate music and fx on the fly via their HW/chips/synthesis.
While from a high level view this still means that some(!) of that could be captured and simply played back, its not always possible, due to how some machines audio hardware works and which sound commands it can digest and process to drive the synthesis/mixing/etc. This is what i meant with 'translated into some interpretation' for Altsound. Sometimes this interpretation can be close (most sound of most WPC machines), sometimes it can't (majority of emulated machines, especially all older ones).

This brings me back to my initial point: Preservation. PinMAME can also be used within of real pinball machines instead of the original boards (e.g. Lisy project), so all of the mentioned other factors you listed are then void, and we want to be as close to generating the same digital(!) output as the original machines.

But then again, as your main ask is a "Minimum audio level", why not simply offer an option to boost the sound above 100%? Wouldn't that be enough? Why use Altsound for just having a per-game volume slider?

Apart from that, we offer since 3 years the following (from whatsnew.txt):
```
PinMAME(32): Added an Automatic Sound Dump functionality:
 Started via F6 (instead of the Recording function via F5) and 
 skips automatically to the next sound / creates a new file if there
 is no sound at all anymore (silence) or the length reaches 4mins.
 The dump stops automatically after soundcommand 0xFF (=max 256 overall generated sounds).
 There is also an altsound CSV created with the dumps. This one can be
 altered with lucky1's Altsound Editor.
```

As for mono vs stereo: As the PinMAME source base goes back over 20 years, back then saving resources was still a thing.
But i could also offer a always-force-stereo option.

**Comment by Ltek** [comment]
Got it, now I get your point on the emulation. 
I did not know about the F6 AltSound auto-dump; seems like a well hidden secret (unintentionally of course). In all my searches I never found posts on the forums or facebook groups... I'll try it. I have a few ROMs that as super low volume even when boosting with PinVol.

thank you for looking at adding the Center -> L/R conversion... I have seen a lot of posts on that one, and thus we must install EQ/APO to remedy... having it built-in will help avoid a lot of confusion and Q&A.

**Comment by toxieainc** [comment]
@Ltek  The 'Center -> L/R conversion' option has been added to the options, please verify.
The rest i will look into later-on.
