### ISSUE TITLE
Getaway solenoid issue

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#157]
https://www.youtube.com/watch?v=NBkTzrCooGY&t=282s
(repro: get to 'supercharger ready' (4th gear), seems to be the diverter being triggered way too often?)

Binary search so far: Not there in 3.5, there at least since March 2023, so i think that this is due to @vbousquet 's solenoid changes, but not sure yet.

**Comment by toxieainc** [comment]
Actually it was https://github.com/vpinball/pinmame/commit/3121d626cd8e2bbbb85fe8de0728b68676f8da92 and so the sound effect is not coming from the diverter, but from the GI.
The question now would be: Is the changed behavior in this table expected (i.e. old/now-wrong assumptions by the author), or needs something to be improved in the new GI code?

**Comment by vbousquet** [comment]
I had a quick look for this to the schematics, the driver and the table. Here are my findings so far:
- the table does not implement WPC GI and play relay sound when GI goes on and off. This is just wrong and explains why there is that problem and linked to the GI => table has to be updated (implement fading, do not play relay sound, these are triacs)
- the diverter is a bit special as it uses a 2 winding coil, with a power coil on solenoid #1 and a hold coil on solenoid #10. This should also be implemented to get correct behavior. The table only takes soenoid 10 in account => table has to be updated on that part too
- I also had a look at the driver and everything looked fine :)

So, I would say table problem and this can be closed

**Comment by vbousquet** [comment]
I went a bit further and implemented the fixes to the table and I can confirm it works. So this can be closed as this is a table issue

**Comment by toxieainc** [comment]
@vbousquet Could you please post the changed script here? Thanks..

**Comment by vbousquet** [comment]
To fix the existing table, just remove the relay sound from the GI callback and it will be good.

To push forward, you can set all the fader of all lights in the table to 'LED (None)' and replace the script by the one below.
You will get the full thing (with the GI blinking during super charger, and all the light shows as they are on the rteal table)

[hs2.txt](https://github.com/vpinball/pinmame/files/13998950/hs2.txt)
