### ISSUE TITLE
Hawkman (Taito 1983) and most of the Taito tables freeze and crash VPX when Quit

### ISSUE THREAD

**Issue by Mrtr32** [vpinball/pinmame#162]
This issues arrive with the latest build of VPX 1448 and somes of the previous builds

Somes of the others noticed table crash:

Lortium (Juegos Populares 1987)
Lunelle (Taito 1981)
Shock (Taito 1979)
Shark (Taito 1982)
Rally (Taito 1980)

The crash is intermittent
No crash dump file has been created by VPX

VPX8 x86 build 1448
B2SServer-2.0.4-ca459cc-Release-win-x86
VpinMAME 3.6 x86 build 607
dmdext-2.2.1-SNAPSHOT-r14

Thanks for all your work!

**Comment by toxieainc** [comment]
Also filed as https://github.com/vpinball/vpinball/issues/783, as unclear so far if VPX or PM bug.

**Comment by Mrtr32** [comment]
I tried some previous VMP and VPX builds with the same issue.

I will rolling back to more older VPM and VPX build to see where the bug appeared.
I will inform you if I find somethings.

**Comment by toxieainc** [comment]
That always helps a lot, thanks!

**Comment by Mrtr32** [comment]
Rolling back to VPinballX-10.8.0-1347-3d585e7-Release-win-x86
VPinMAME-sc-3.6-560-350864b-win-x86
Same issue

**Comment by Mrtr32** [comment]
Tested **VPinballX-10.7.4-417-5a3439f-Release-win-x86**
VPinMAME-sc-3.6-607-51667e2-win-x86
No Crash on exit issues anymore with all the Taito and and others tables mentioned at the previous post
This is not a **VPM** issue so a **VPX8** issue.

**Comment by toxieainc** [comment]
According to https://github.com/vpinball/vpinball/issues/783 it seems(!) like only the sc (colorized sam support) builds show this issue.

**Comment by Mrtr32** [comment]
@toxieainc

This Why I always write the complete name and the build in post to help isolating the issue

**Comment by passionforpins** [comment]
> According to [vpinball/vpinball#783](https://github.com/vpinball/vpinball/issues/783) it seems(!) like only the sc (colorized sam support) builds show this issue.

That's what I've narrowed it down to in my extensive tests. Any non -sc version like 3.5 and the newest 36.6 vpinmame.dll's work fine with Taito tables I've tested. any -sc version will lockup the table upon quitting

**Comment by Mrtr32** [comment]
Good work passionforpins and thanks for your precious help

**Comment by Mrtr32** [comment]
Tested VPinMAME-3.6-607-51667e2-win-x86 **non SC version** and the Lunelle taito table show me the same issue.
Really Weard!

**Comment by passionforpins** [comment]
try the non -sc vpinmame 3.5 dll. sorry I dont have lunelle

**Comment by Mrtr32** [comment]
Tried **VPinMAME-3.5-225-1e9f092-win-x86** Non Sc version with Hawkman show me the same issue
Simply hitting q two time to quite the table and VPX freeze

**Comment by toxieainc** [comment]
Unfortunately i have no repro whatsoever. Is this also happening without B2S and DMDext for you guys?

**Comment by Mrtr32** [comment]
Yes tested without b2s and on my test computer, I don’t use dmdext, only Virtual DMD
I will check in the table script if I find some things
I think all the Taito tables has been made by jpsalas
Not sure if those tables should be updated

**Comment by passionforpins** [comment]
Yesterday after changing to non -sc vpinmame dll's I could get a lockup but today Hawkman locked up after the second start of a game (after fully closing vpx and starting fresh) I'm completely at a loss to whats happening now. Pic attached shows vpx player sucking up 30% of my memory and 13% of the cpu cycles while locked up.
![hawkman-lockup](https://github.com/vpinball/pinmame/assets/52011304/c4fa53d7-b1b3-4b66-92fd-774312ec0bf6)

**Comment by Mrtr32** [comment]
Ok I found what subroutine that causing the freeze and crash issue with this taito table
In the Hawkman table script you have one special subroutine named **NVramPatchExit**
As Workaround for the crash I simply removing the NVramPatchExit subroutine and the table don`t crash anymore when exit
 The line 146 from original table is:
146 Sub table1_exit:NVramPatchExit:Controller.stop:End Sub

Removing **NVramPatchExit** just before Controller.stop solved the issue

The line must be like that:
146 Sub table1_exit:Controller.stop:End Sub

I don`t know what the **NVramPatchExit** do and if it is necessary so this sub routine is the raison why the table crash on exit.

**Comment by passionforpins** [comment]
Awesome find @Mrtr32 . Now we have to search that in every taito table script I suppose :)

**Comment by passionforpins** [comment]
I had to comment out whole subs with nvrampatch et al but the table still works and quits just fine now as far as I can tell.

**Comment by Mrtr32** [comment]
I asked jpsalas on the vpforums about that sub routine because I don`t know if it is necessary with the current VPM and VPX builds.

I don`t know why this subroutine is present in all the Taito tables scripts?

**Comment by Mrtr32** [comment]
I will close this issue because it is not related to VPM.
