### ISSUE TITLE
Can't fetch upstream repo

### ISSUE THREAD

**Issue by droscoe** [vpinball/pinmame#163]
I noticed today that I am no longer able to fetch upstream/master from this repository

```
$ git fetch upstream/master
fatal: 'upstream/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This was working fine previous, and I can't see anything changed/wrong

```
$ git remote -v
origin  git@github.com:droscoe/pinmame.git (fetch)
origin  git@github.com:droscoe/pinmame.git (push)
upstream        git@github.com:vpinball/pinmame.git (fetch)
upstream        git@github.com:vpinball/pinmame.git (push)
```

**Comment by toxieainc** [comment]
Works for me. Also nothing has been changed.
Do you already have the new 2FA in place that github requires (forgot which date this is due, maybe already now)?

**Comment by droscoe** [comment]
> Works for me. Also nothing has been changed.
> Do you already have the new 2FA in place that github requires (forgot which date this is due, maybe already now)?

Hmmmm.  That could be it, If the 2FA became required over the last few days.  I’lol set it up.  If it resolves, I will update here

**Comment by droscoe** [comment]
Enabled 2FA and it didn't help.  I can update my fork from within github, but its not working any longer from git bash.  I'm going to re-clone the repo and see if that resolves the issue

**Comment by droscoe** [comment]
I re-cloned the repo with the same results.  The issue is on my end.  This command works:
```
git fetch upstream
git rebase upstream/master

```
But not

`git fetch upstream/master`

I swear this was working before, but in any case, "git fetch upstream/master" is incorrect syntax.  The problem is resolved.
