### ISSUE TITLE
Avengers LE: flippers still work after the game is over / avs_170h misses fast flips

### ISSUE THREAD

**Issue by Loafmeister** [vpinball/pinmame#164]
For any of the Avengers LE tables done (example: try JPSalas' latest available at VPF here:  https://www.vpforums.org/index.php?app=downloads&showfile=14537), the flippers are still working even before you start a game or after game over.  Note two things:

- this does not occur on the PRO
- I used to own an Avengers Hulk LE and this did not occur on the real pin, when not in game, the flippers were dead as expected

VPM team: thanks for all the work you do

**Comment by toxieainc** [comment]
Yup, just tested. Its basically the problem of the fast flips shortcut. One would have to find the matching address for avs_170h for this to work correctly.

**Comment by toxieainc** [comment]
@Loafmeister Please verify..

**Comment by Loafmeister** [comment]
Will do so shortly (2 hours or less), stand by…

**Comment by Loafmeister** [comment]
I can confirm flippers are now dead outside of in game, well done.  I'm getting no music though in game on Avengers but that's another issue I'm looking into and if others can confirm, I'll open a separate ticket.

**Comment by Loafmeister** [comment]
Toxie: your commit indicates the following:  Implemented fast flip for avr_120h, avs_170h, im_186, im_186ve, mt_145, mtl_180, rsn_110, sman_261, st_162, st_162h, trn_174, wof_602h and xmn_151

Quite a few of those roms are NOT the limited edition versions of those tables (I'm looking at Tron as an example).  Was this issue limited to the LE for Avengers and is this fix correcting other LE's?  if yes, should it not be applied to trn_174h in the case of tron?

**Comment by Loafmeister** [comment]
Ok if I understand correctly that means tron_174h and xmn_151h already had this support?

**Comment by toxieainc** [comment]
In theory, yes. But needs verification.

**Comment by CarnyPriest** [comment]
Yes, DJRobX put in support for those sets years ago.
