### ISSUE TITLE
Quijote (Juegos Populares 1987), Lortium (Juegos Populares 1987) and Faeton (Juegos Populares 1985) roms crash VPinMAME on exit

### ISSUE THREAD

**Issue by Mrtr32** [vpinball/pinmame#166]
To reproduce the issue:

Do a rom test with VPinMAME-sc-3.6-617-0e7137f-win-x86

Tested roms:

pimbal.zip
lortium.zip
faeton.zip

Click Setup.exe, Start the rom, Stop the rom and VPinMAME freeze and not responding.

**Comment by volkenborn** [comment]
Just an idea:
J. Populares is on of the manufacturers who pulse the NMI line on shutdown to save the NVRAM.
Therefore we need to execcute a few CPU timeslices on reset / exit. 
Maybe that won't go down well when done by the DLL?

**Comment by volkenborn** [comment]
[VPinMAME-3.6-663-2deaaec-win-x64.zip](https://github.com/vpinball/pinmame/files/13714687/VPinMAME-3.6-663-2deaaec-win-x64.zip)
[VPinMAME-3.6-663-2deaaec-win-x86.zip](https://github.com/vpinball/pinmame/files/13714688/VPinMAME-3.6-663-2deaaec-win-x86.zip)

@Mrtr32 Could you try with these builds again? I reduced the timeslices if no sound CPU is present; looks fine here...

**Comment by Mrtr32** [comment]
Hi volkenborn!

Tested and I can confirm the crash freeze issue when quiting the table is fixed! :-)
Vpinmame dont crash anymore on rom test too!

Thank you very much for the fix!!!
