### ISSUE TITLE
Make it possible to recognise the VPinMAME window form by its title.

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/pinmame#171]
B2SWindowPunch is a small tool which uses regular expressions to recognise window forms by its titles of DMDext, B2S Server and Pinup Player. 
It works very well for all of them because they can all be identified by the name of the form using a regular expression like this:

These are the windows cutting from
^B2S Backglass$|^B2S Backglass Server$|^B2S DMD$"
These are the forms cutting:
^Virtual DMD$|^Virtual Alphanumeric Display$|^PUPSCREEN[0-9]+$

to get the same working for VPinMAME isn't working because it shows the internal gamedriver description in the title.

Would it be possible to put a text in the beginning of the string called "VPinMAME:" like this in (src/windows/window.c) :

// line 507 - 511
// make the window title
#ifdef VPINMAME
	sprintf(title, "**VPinMAME:** %s", Machine->gamedrv->description);
#else
	sprintf(title, APPNAME ": %s [%s]", Machine->gamedrv->description, Machine->gamedrv->name);
#endif

**Comment by toxieainc** [comment]
Good point, thanks for the patch!
