### ISSUE TITLE
Raspberry PI builds broken

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#172]
```
The following packages have unmet dependencies:
 libasound2-dev : Depends: libasound2 (= 1.2.8-1+b1) but 1.2.8-1+rpt1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

@jsm174 @bontango Any clue what needs to be done?

**Comment by bontango** [comment]
I'm only guessing here, but looks like the build environment did an automatic update of the libasound2 library without updating the libasound2-dev library, hence the dependency error. We need to wait for an updated -dev package which IMHO is no available yet.

**Comment by toxieainc** [comment]
Yup, seems like the issue has fixed itself by now, thanks!
