### ISSUE TITLE
Guns and Roses controller button 9 enters Rom Audit

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/pinmame#173]
Guns and Roses controller button 9 enters Rom Audit and its my left flipper. Only this table so far

**Comment by Loadedweapon** [comment]
It is on the new VPW Guns and Rose's table.

**Comment by toxieainc** [comment]
Thats really weird. Could you please try https://www.vpforums.org/index.php?app=downloads&showfile=14313 if the same happens?
Cause i don't understand how this can be related to the emulation, i suspect its a sideeffect of the VPW version somehow.

**Comment by Loadedweapon** [comment]
Hmm yea I guess it's a table issue. this one works fine.. I will post it on on VPU Thank you!
