### ISSUE TITLE
ROM Sounds not playing in certain games: 64bit

### ISSUE THREAD

**Issue by WrinkleRelease** [vpinball/pinmame#176]
---Bug withdrawn. Re-installing the current beta build seemed to fix the problem.---

**Issue**
ROM sounds do not play for some ROMs in 64bit 10.8. 

**Behavior**
Loading certain table gives table sounds only with no sounds from the ROM. This problem is not present in 32bit 10.8, only 64bit. Sounds are enabled in VPX (again, this isn't a table sound issue. It is ROM sounds only).  Use Sounds is also checked in VPinMAME for these ROMs.

**Tables Effected**
I've encountered this on at least two tables:
1. Tales of Arabian Knights (totan_l4)
2. Transporter - The Rescue (tsptr_l3)

I am running VPX as a stand-alone application. It is not being launched through a front-end.

**Comment by toxieainc** [comment]
I just checked, this works for me. Could you please try the setup64.exe -> Test
if the sound plays then?

**Comment by WrinkleRelease** [comment]
Thanks for the reply. My issues above were fixed by simply deleting and re-installing the VPinMAME exe files. 

Sound issues persist, but they are intermittent and not confined to any specific ROM. The behavior is thus: occasionally, ROM sounds will totally stop on VPX 10.8 builds, both 32 and 64 bit until I shut down any VPX instances and restart them. 

For example, I was testing ROMs yesterday and left the VPinMAME testing app open with no ROM running. This ended up causing lost ROM sounds in the 64 and 32bit VPX builds until the VPinMAME tester and VPX exe files were closed and re-opened. 

So, this could very well be a VPX problem. Maybe 10,8 isn't playing nice with 3.6? I have nothing to help you figure it out I'm afraid so this thread can be closed.

**Comment by toxieainc** [comment]
Weird, but seems to be some problem with your sound setup then?
