### ISSUE TITLE
Add muted ROM entry

### ISSUE THREAD

**Issue by Rappelbox** [vpinball/pinmame#178]
This issue/enhancement suggestion was originally posted by Dazz back in 2019 but I thought it could be interesting again.

Nowadays lots of tables use puppacks with integrated music, rethemed and modded tables where the music simply doesn't fit anymore.

Suggestion would be to allow a sort of automated naming convention like "_mtd.zip" as a marker for muted ROMs.

Examples:
acd_170hc.zip --> acd_170hc_mtd.zip
simpprty.zip--> simpprty_mtd.zip
trn_174h.zip --> trn_174h_mtd.zip

This way ROM collections could be consistent and easier to manage without extensive scripting, copy-pasting ROMs.

**Comment by francisdb** [comment]
What's the difference between a muted rom and the table setting the rom volume to 0?

**Comment by toxieainc** [comment]
I agree. The standard should be that a respective table should just mute the rom on start and unmute again on close.
This is much less confusing to the enduser as having additional sets or aliases.
