### ISSUE TITLE
Metallica Premium Monsters (Stern 2013) Insert lighting Issue

### ISSUE THREAD

**Issue by miraculix33** [vpinball/pinmame#191]
From rev VPinMAME-sc-3.6-734-9b6345e i had the Issue that the Arrow Lights on Orbits, Ramps, Graveyard and the dead end shot are no more lite up, all other lights are normal.

**Comment by toxieainc** [comment]
@miraculix33 Can you please test with https://github.com/vpinball/pinmame/actions/runs/7513595385 again?

**Comment by miraculix33** [comment]
@toxieainc Works perfect now, thanks
