### ISSUE TITLE
AC/DC GI not working in the latest builds

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/pinmame#192]
AC/DC GI not working in the latest builds works in 653 which is what I had before updating to 752 so not sure how far back it is broken.
I went back to 653 and is working again. Just tested 730 and it's working..

**Comment by toxieainc** [comment]
Could you please retry with https://github.com/vpinball/pinmame/actions/runs/7513595385 ?

**Comment by Loadedweapon** [comment]
Yes that fixed it. Thanks Toxie!
