### ISSUE TITLE
Metallica Premium Monsters (Stern 2013) coffin hammer magnet issue

### ISSUE THREAD

**Issue by miraculix33** [vpinball/pinmame#198]
Hi, i have noticed that the coffin hammer magnet holds the ball for too short a time, the ball rolls away before the hammer strikes, (tested with rev VPinMAME-sc-3.6-732-893da42-win-x64, there is it ok)

**Comment by toxieainc** [comment]
could you please retry with https://github.com/vpinball/pinmame/actions/runs/7594434058 ?

**Comment by miraculix33** [comment]
didn't help, it's still exactly the same as before, and the skillshot doesn't work properly. the up-post moves in and out very quickly

**Comment by vbousquet** [comment]
I have just looked in details into this issue. To put it short, my understanding is that the old code was wrong and it's no right but the consequence is that the table has to be updated.

Metallica has a magnet board processor (with its own microcontroller) that the main board drives, selecting one of 4 mode of operations. I have documented them in the code from the scematics and online ressources (missionpinball is the best there):
```
// Operation mode is written here with the 2 highest bits D6/D7 of Aux Data wired to the board, and strobed here.
// 00 => Off
// 10 => Grab: activate magnet for 1 second then switch it off. It grabs the ball from centimeters away
// 01 => Detect: detect ball and report it to switch 63
// 11 => Detect & Hold: detect ball, if detected report to switch 63 and also grab it
// See https://missionpinball.org/mechs/magnets/stern_magnet_pcb/ for a detailled description:
```

So the table has to emulate this and it does not at the moment. I think it used to work because the old code was wrongly considering these data outputs as modulated lights and performing some fading, therefore reporting delayed state transitions.

**Comment by miraculix33** [comment]
@vbousquet Thanks for the detailed explanation, so I will solve the whole thing in such a way that I probably leave my 32bit on version 3.6-732-893da42-win-x86 and wait for a possible solution, since the table runs perfectly with 32bit

**Comment by vbousquet** [comment]
If you are using VPW version (1.1.5) of the table, here is a modified script that adds it:
[Metallica_script_fix.txt](https://github.com/vpinball/pinmame/files/14000544/Metallica_script_fix.txt)

**Comment by miraculix33** [comment]
where can i find version 1.1.5, i only see 1.1 for download

**Comment by vbousquet** [comment]
My bad, here is the script for version 1.1:
[Metallica_script_fix(1).txt](https://github.com/vpinball/pinmame/files/14000575/Metallica_script_fix.1.txt)

**Comment by miraculix33** [comment]
@vbousquet I tested the script, but now the magnet no longer works at all

**Comment by vbousquet** [comment]
You also need to update to PinMame with the latest fixes: https://github.com/vpinball/pinmame/actions/runs/7597779141

**Comment by miraculix33** [comment]
@vbousquet i´ve already done that--> no magnet. used a fresh mtl_180h rom from stern

**Comment by vbousquet** [comment]
I have talked with the VPW table author. The fact is that the table used to rely on the bug and they adjusted around it for the table VPX to work. We could maintain the bug, but on the other hand with the current (fixed) version, they are preparing an update that works fine, and is true to the real table. So, I think we should keep the right code (yet breaking most existing versions of this table that rely on the 2 bit binary command being wrongly smoothed out like a lamp on a per bit basis).

**Comment by toxieainc** [comment]
I agree, then lets wait for the new table version. Other versions will hopefully be adapted, too.
