### ISSUE TITLE
Machine Bride of Pinbot crashes in new PWM code

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#201]
For details, see https://github.com/vpinball/vpinball/issues/1377

**Comment by francisdb** [comment]
SIGSEGV

```
<unknown> 0x0000000000000000
core_write_pwm_output_8b 0x00007ffff574d93d
HC4094_oe_w 0x00007ffff56874c3
init_bop 0x00007ffff5789c49
run_game 0x00007ffff56af6ea
StartGame(int) 0x00007ffff57b88af
<unknown> 0x00007ffff4ee6333
start_thread 0x00007ffff4a97ada
clone3 0x00007ffff4b2847c
```

**Comment by Dicentim974** [comment]
Hi guys, I went here to report this issue with BOP, and I see you noticed it before. I tried to reverse to VPinmame 3.5 and it's working back. But some other games require 3.6.
Hope a fix will be found.
Regards.

**Comment by Dicentim974** [comment]
I can add that on Grease (2023) table, the game doesn't release any ball when launching a game. Of course I tried to delete elvis.nv

**Comment by Dicentim974** [comment]
Issue solved for The Machine : BOP using this rom : https://mega.nz/folder/WJ90GBCS#SRZWCHXJfOIyrvL2x6Oimg

**Comment by toxieainc** [comment]
@Dicentim974 Please file a separate github issue for Elvis/Grease.

**Comment by toxieainc** [comment]
@smilelikejoker please test with https://github.com/vpinball/pinmame/actions/runs/7665532601

**Comment by toxieainc** [comment]
@Dicentim974 Same, plus the Elvis issue may also be fixed with this build? (don't know for sure though)

**Comment by Smilelikejoker** [comment]
> @Smilelikejoker please test with https://github.com/vpinball/pinmame/actions/runs/7665532601

Negative.  Still crashing with that action.

**Comment by toxieainc** [comment]
Uhm, thats pretty weird though (the part with the audio)..

**Comment by Smilelikejoker** [comment]
> Uhm, thats pretty weird though (the part with the audio)..

It was a smaller issue that was easily fixed by turning off PWM render mode in the table options.  It wasn't always like that either.

**Comment by volkenborn** [comment]
I noticed in core.c there is a special handling for the CFTBL chase lights:
      `if (core_gameData->hw.gameSpecific2 == WPC_CFTBL) // CFTBL chase lights`

Maybe something similar must be done for the head lamps of BOP? These run off WPC_SOLENOID1, not WPC_SOLENOID3.
Also, more games use the HC4094 to drive extra features, like AFM, WW, CP etc.

**Comment by volkenborn** [comment]
Should be fixed now, please try again with latest builds

**Comment by Smilelikejoker** [comment]
No longer crashing :)  Not sure of any weird table effects, but we can play it again lol.

**Comment by toxieainc** [comment]
@vbousquet to close/verify
Thanks @volkenborn !

**Comment by vbousquet** [comment]
Just had a look and it is clean from my point of view. @toxieainc you can close this one.
Thanks all!
