### ISSUE TITLE
Broken laser war segments 

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#205]
Master branch
Same happens in vpinball

```
./build/xpinmame -rompath ~/.pinmame/roms -nvram_directory ~/.pinmame/nvram  lwar_a83
```

[Screencast from 2024-01-26 17-50-21.webm](https://github.com/vpinball/pinmame/assets/161305/ce8db6d3-f5e7-47a5-bb56-7e2eff2f2979)

**Comment by volkenborn** [comment]
Whoops, that was a side-effect of the display lock done for S11 games.
As I already assumed, probably BK2K has an error in its display routine for a bad U26 game ROM.
Would love to see a bad ROM running in a real game; I'd say the error shows up there as well.
Anyway, excluded all DE games for the lock now...

**Comment by francisdb** [comment]
I don't understand any of what you just wrote but let me check tomorrow if it's fixed 😅

**Comment by francisdb** [comment]
Confirmed fixed

![image](https://github.com/vpinball/pinmame/assets/161305/276e95ec-f7c9-48f8-aaf7-58a2ec911500)
