### ISSUE TITLE
bugs bunny birthday ball german rom

### ISSUE THREAD

**Issue by sting932003** [vpinball/pinmame#206]
<game name="bbnny_lg" romof="bbnny_l2">
		<description>Bugs Bunny&apos;s Birthday Ball (LG-2 German)</description>
		<year>1990</year>
		<manufacturer>Bally</manufacturer>
		<rom name="Bugs_Bunny_U26_LG-2_Nova_Apparate.bin" size="16384" crc="0ba81bae" sha1="ce56eadf26ee74a3a7b185893dceb09dc4929fa8"/>
	</game>. the crc and shai matches. its calling 32768 instead of 16384

**Comment by toxieainc** [comment]
You are right.. We forgot to remove the dupe in the second 16k/mirror..
Thanks!

**Comment by toxieainc** [comment]
..and fixed
