### ISSUE TITLE
SIGSEGV when running Sorcerer (Williams 1985)

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#207]
Master branch

Signal: SIGSEGV (Segmentation fault)

```
./build/xpinmame -rompath ~/.pinmame/roms -nvram_directory ~/.pinmame/nvram sorcr_l2
```

```
drawChar core.c:2087
video_update_core_status core.c:1751
video_update_core_gen core.c:1394
force_partial_update mame.c:1196
draw_screen mame.c:1216
updatescreen mame.c:1359
cpu_vblankcallback cpuexec.c:1626
timer_adjust_global_time timer.c:316
cpu_timeslice cpuexec.c:889
cpu_run cpuexec.c:421
run_machine_core mame.c:593
run_machine mame.c:528
run_game mame.c:338
main main.c:106
__libc_start_call_main 0x00007ffff76280d0
__libc_start_main_impl 0x00007ffff7628189
_start 0x0000555555840335
```

**Comment by toxieainc** [comment]
@vbousquet This is due to `drawChar(bitmap, locals.firstSimRow + startRow, thisCol, coreGlobals.diagnosticLed, CORE_SEG7, 0);`
(i.e. dimming == nullptr)

**Comment by volkenborn** [comment]
But even if you check dimming for existance before, the credit / BIP displays are corrupted:
![sorcr_l2](https://github.com/vpinball/pinmame/assets/3236140/1d247151-aaa2-49bd-a1e2-24af792ec932)

**Comment by vbousquet** [comment]
You mean, there was a bug before the change for dimming ?

**Comment by toxieainc** [comment]
I would guess that the intended behaviour would be: if dimming exists, then use it, if not, use previous code? But @vbousquet that would be up to you (don't know if there should also be dimming implemented for that)

**Comment by volkenborn** [comment]
Seems so...
the new segment drawing routine didn't take into account the smaller digits, which can be even smaller if the -dmd_compact option is used.
I believe I have fixed the issue (including the null pointer), please verify.

**Comment by francisdb** [comment]
No longer crashing here. Thanks.

**Comment by toxieainc** [comment]
Please just leave it open some more for Vince to verify if this is the new intended behavior, or if something is still missing.

**Comment by vbousquet** [comment]
Just checked and it seems good to me too. @toxieainc you may close!

**Comment by toxieainc** [comment]
Cool!
