### ISSUE TITLE
VPinMame is not backwards compatible when UseVPMModSol=True for The Simpsons Pinball Party

### ISSUE THREAD

**Issue by apophis79** [vpinball/pinmame#215]
**Describe the bug**
An unreleased version of The Simpsons Pinball Party (TSPP) was developed using an earlier beta version of VPM 3.6 to utilize the PWM output provided for solenoids, where the output ranges from 0-255. Note, this capability is not available for TSPP in VPM 3.5 but it became available in 3.6 beta around March of 2023. In the latest version of VPM 3.6 the PWM output is no longer available when UseVPMModSol=True (nor when UseVPMModSol=1). 

**To Reproduce**
1. Download this version of TSPP: https://drive.google.com/file/d/1bflrGCHro2rT5CYCBGv8h3wQVVBjWIF_/view?usp=sharing
2. Run the table, and press D to open the debugger window.
3. Start playing the game and you will see message like "Lampz.SetModLamp aInput=1" and "Lampz.SetModLamp aInput=0". These are displaying the raw solenoid PWM outputs that are used to drive the flashers.

**Expected behavior**
The debug print results should show aInput=0 up to aInput=255 when flashers are flashing.
You can verify that UseVPMModSol= True by typing into the debug window: debug.print UseVPMModSol
It will return -1 which is the numerical value for "True"

**Versions & Settings**
 - VPinMame: https://github.com/vpinball/pinmame/actions/runs/7756977911
 - VPX: v10.8.0 Beta (Rev. 1879 (e7ea030), windows OpenGL 64bit
 - Windows 11

**Comment by vbousquet** [comment]
Just had a look and the table is missing the call to vpmInit. This call is needed (and was needed before) to correctly support pause/resume/exit and modulated solenoid. I did not find any real PinMame bug here but it's true that the preliminary implementation did not check that modulated solenoid were enabled (which in fact was a bug, it should have checked for that). The solution here is to update the table by adding `vpmInit Me` inside the `table1_init` sub of the script.
