### ISSUE TITLE
RESOLVED: Flashers not functioning properly.

### ISSUE THREAD

**Issue by GHOSTfaceKILLr1974** [vpinball/pinmame#217]
Flashers are no longer working properly (mostly Stern tables) like ACDC, Elvis, Star Trek LE, Iron Maiden, Xmen, Ironman. Some flashers wont turn on and others are extremely faint.
Elvira Scared Stiff is the opposite where the flashers are extremely bright and wont turn off.

I have vpx 10.8.0 rc1 and vpinmame 3.6 beta running on desktop.

**Comment by francisdb** [comment]
I think this was recently fixed in 15b7c6d

**Comment by GHOSTfaceKILLr1974** [comment]
> I think this was recently fixed in [15b7c6d](https://github.com/vpinball/pinmame/commit/15b7c6d1e22144fb988635998f636ef04df0c9c9)

I'm currently on 66be20f with flasher issues.

**Comment by vbousquet** [comment]
This is supposed to be fixed. Could you try with the latest builds ?

**Comment by GHOSTfaceKILLr1974** [comment]
> This is supposed to be fixed. Could you try with the latest builds ?

I'm on v3.6-822-66be20f (pre-release) which I thought was the most current build.
Can you send me a link to the latest build. I'm not that good navigating through Github.

**Comment by vbousquet** [comment]
It's here: https://github.com/vpinball/pinmame/actions
You need a github account for this

**Comment by GHOSTfaceKILLr1974** [comment]
> It's here: https://github.com/vpinball/pinmame/actions You need a github account for this

Flasher issue resolved by installing latest build. Thank you vbousquet.
