### ISSUE TITLE
ij4_210 erratic flipper behavior

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#219]
Flippers go on an off during other rom events.

Tested on 10.8.0 RC1 Windows GL
VpinMAME f7995d8 

**Reproducer**

1. Play any "Indiana Jones (Stern 2008)" table tat uses `ij4_210`.
2. Launch a ball
3. Hold up the flippers
4. You will see them going off an on during certain callouts/events.

Could this be related to #196

**Comment by zognic** [comment]
https://github.com/vpinball/pinmame/assets/55721851/cefedf52-3e89-47eb-b6a9-5158eec55d23

**Comment by toxieainc** [comment]
@francisdb Why #148??

**Comment by toxieainc** [comment]
maybe #196 ?

**Comment by francisdb** [comment]
Oops, indeed wrong link.

**Comment by toxieainc** [comment]
I cannot repro on Indy, but only the 'WOF sticky flipper issue'. Tested via 10.7.4.
@vbousquet for vis

**Comment by vbousquet** [comment]
I have it on Indy (I started having a look then got sidestepped rewrote the aux boards which were also a bit wrong).

**Comment by toxieainc** [comment]
@francisdb Please confirm the IJ4 fix..

**Comment by francisdb** [comment]
Confirmed fixed here :+1:

**Comment by zognic** [comment]
Fixed here too , thanks a lot
