### ISSUE TITLE
AltSound:  Incorrect parsing for some WPC generations

### ISSUE THREAD

**Issue by droscoe** [vpinball/pinmame#220]
This bug affects:

```
GEN_WPCDCS
GEN_WPCSECURITY
GEN_WPC95DCS
GEN_WPC95
```

I was approached with a strange problem with the Theatre of Magic altsound.  On the first ball, the sounds were either not playing or playing the wrong samples.  On ball 2, the problem resolves itself.

Looking at the code, I see the following:

`((cmd_buffer[2] == 0x00) && (cmd_buffer[1] == 0x00) && (cmd_buffer[0] == 0x00))) // glitch in command buffer?`

When this case is hit, the command is filtered.  This is a mistake.  First, these are 16-bit commands.  Filtering a command based on three arguments will skew all downstream commands by one byte.  This was the issue with Theatre of Magic as can been seen in the following capture of incoming commands:

```
INFO: Received CMD: 00
INFO: Received CMD: 00

INFO: Received CMD: 00
INFO: Received CMD: 02

INFO: Received CMD: 02
INFO: Received CMD: 00
```

The code receives two consecutive 0x00 bytes and correctly filters them.  However, they still remain in the 4-byte command buffer.  The buffer is 4-bytes because some ROMs will send a two-byte control code, with the metadata contained in the following two-bytes.  That is not a problem.  Consider the code snippet above and the recorded commands.  The third 0x00 byte triggers the line of code that will filter it, assuming a "glitch in the command" buffer.  However, the correct command that follows the 0x0000 command is indeed 0x0002.  By filtering out those three bytes, the cmd instead becomes 0x0202.  In the case of TOM, this is also a valid sample, but incorrect.  From this point forward, all parsed commands will be wrong resulting in either no playback or incorrect playback.

That it resolves itself on ball 2 is a happy coincidence.  I have a fix for this issue, which is a simple matter of removing the line that checks for three consecutive zeros.  If this was ever truly a problem, a better fix is needed that does not risk creating an off-by-one issue with all downstream commands

**Comment by toxieainc** [comment]
Unfortunately i don't remember why i added this case. Might well be that it was 'necessary' in the beginning, when the whole altsound code was still much simpler and still more buggy.
