### ISSUE TITLE
VPinMAME save settings only in registry ?

### ISSUE THREAD

**Issue by Augusto7743** [vpinball/pinmame#221]
Thanks for reading my topic.
Visual PinMAME current version only save settings in registry ?
The settings are in path below ?
HKEY_CURRENT_USER\Software\Freeware\Visual PinMame

I only want save settings avoiding reconfigure in each WINE installation.
Save settings in ini files too ?
Have an nice day.

**Comment by toxieainc** [comment]
See #170

**Comment by toxieainc** [comment]
Dupe, thus closing

**Comment by Augusto7743** [comment]
Thanks for sharing the issue 170 and closing that topic.
