### ISSUE TITLE
ft_l5: fish tales, balls get stuck in fishing reel

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/pinmame#223]
I am now trying 1.0.1 of the table and I get the exact same behaviour, as in 1.0.0 that after 2-3 locked balls, they sort of get stuck.
Using VPX 10.8-1873 and VPM 3.6-822

![image](https://github.com/vpinball/pinmame/assets/12571104/69b70d3d-53f9-4098-824a-d87c49e8b3bd)

the top locked balls marked in red stay in that position even if the game ends. (which I suppose it shouldn't)
One ball got inside the fishing reel, but it seems to stay there. the bottom marked part (looking like a ball) triggers, but there is nothing to kick away...

**Comment by toxieainc** [comment]
@vbousquet for vis

**Comment by JockeJarre** [comment]
I have a mobile phone video recording, if it could be of any help. Strange it seems that it only happens to me...

**Comment by francisdb** [comment]
We saw this before on standalone but the latest pinmame changes fixed this. Not sure if they have been released by now.

**Comment by JockeJarre** [comment]
I will check later builds under actions, if it works

**Comment by JockeJarre** [comment]
I tested VPM-3.6-839 now, same here. So you think this is a VPM issue?
My thought was that the ball has physical problems to get through...

**Comment by droscoe** [comment]
This does not appear to be a problem with pinmame.  This looks like a VPX issue, if that.  It could also be a problem with the table itself, which would be outside of both VPX and pinmame.  Am I missing something that justifies this issue being here?

**Comment by francisdb** [comment]
Have not tested 1.0.1 yet. The pwm issue was for a pre 1.0.0 release. Can anybody else reproduce this?

**Comment by vbousquet** [comment]
I had a look but was not able to reproduce so I'm a bit at a lost. I'm not sure this is a VPM problem since all signals seems ok. It may also be a VPX synchronization problem (the table uses a DC motor and optos to stop at the right position, the implementation as an asynchronous script vs emulation is somewhat difficult).

**Comment by JockeJarre** [comment]
Feels a little strange, that it only happens to me. Maybe because my cabinet isn't up to speed with what is needed for the table?

**Comment by JockeJarre** [comment]
This can be closed, the problem comes from the table script as described here https://github.com/vpinball/pinmame/issues/236#issuecomment-1965812926
