### ISSUE TITLE
ACDC - current version broken after Update #833

### ISSUE THREAD

**Issue by sverrewl** [vpinball/pinmame#225]
https://github.com/vpinball/pinmame/actions/runs/7839397894 - tagged "Update #833"

I've tried same ACDC table, same VPX (rev. 1879 and acd_170h rom), different pinmame version.
After this version, VPinMAME-sc-3.6-836 - I'm not sure if it is broken diverter, but, the ball doesn't go into the canon.
Also, if ball goes into "BellK" kicker, (kicker under the bell) it is lost for the rom and ball search kicks in.

I don't see anything from the commits that should explain this, maybe script needs improving because a different change ?

**Comment by vbousquet** [comment]
I would say that's me breaking things with the SAM aux board rewrite. I will have a look but not until next week

**Comment by sverrewl** [comment]
Oh. I thought that didn't get merged to master. Obviously, something I missed. Well, you guys are awesome - got at it. I really applaud you guys for daring. Never seen this much invention and improvement from one minor release to the next. Very impressive work from all of you.
