### ISSUE TITLE
Issue with vpmNudge on Jokerz! when using UseVPMModSol = 2

### ISSUE THREAD

**Issue by apophis79** [vpinball/pinmame#231]
**Description**
The released version of VPWs Jokerz! works just fine. An unreleased version that uses the new ModSol=2 functionality only works fine if the line defining vpmNudge.TiltObj is commented out. Otherwise, the objects in that array are always disabled. 

**Steps to Reproduce**
1. Download this unreleased version of Jokerz! https://drive.google.com/file/d/19oIEOfh_p96h9LxCyN2mEty5BCkGWnBD/view?usp=drive_link
2. Go into the script and uncomment line line 194. This will define the vpmNudge.TiltObj array as is normally done.
3. Play the table an notice that the bumpers and slings are always disabled. 

**Expected Behavior**
If you download and play the released version of Jokerz! it works normally. https://vpuniverse.com/files/file/9971-jokerz-williams-1988-vpw/

**Comment by vbousquet** [comment]
I will have a look. Just another information I need: do you have a `NudgePlugIn.vbs``(custom nudge script) in your script folder ? If yes, could you share it ?

**Comment by apophis79** [comment]
Fixed in build 852. Thanks!
