### ISSUE TITLE
PPUC builds always fail?

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#234]
```
Determining the default branch
  Retrieving the default branch name
  Not Found
```

Has anybody looked into this?
https://github.com/actions/checkout/issues/347

What does PPUC stand for?

**Comment by jsm174** [comment]
> Has anybody looked into this? [actions/checkout#347](https://github.com/actions/checkout/issues/347)
> 
> What does PPUC stand for?

yes, @mkalkbrenner will be fixing this. 

https://github.com/PPUC

**Comment by mkalkbrenner** [comment]
> What does PPUC stand for?

Pinball Power-Up Controller:
https://github.com/PPUC

An alternative to P-ROC and LISY, based on libpinmame instead of a lot of switches within the pinmame code.

I'm working on the issue ...
