### ISSUE TITLE
newer versions causing frame rate issues in many tables

### ISSUE THREAD

**Issue by keithhov** [vpinball/pinmame#236]
Sorry to be so broad...   a graphic intensive table like fish tales is an example.... originally I could play this game with all the graphic stuff on at 4k, 120 FPS steady......I updated 3.6 to a version around 822 and noticed a significant drop in performance, even with graphics options turned down and resolution of 2k and the framerate would drop very often, even without flashers hitting,, example would be ball draining down either side, the frame rate would drop from 120 to around 100 for about 2 seconds as soon as the ball would hit the drain switch. 

Tried all types of testing,,, still would get poor performance on fish tales and johnny mnemonic..........I started going back to older verions of pinmame.......currently went back to version 805 and tables play significantly better, back to 4k and 120 FPS. I even upgraded video card to 4070 super TI and still get the performance issues with recent versions of pinmame. 

I will try to narrow down which version started the issue , somewhere between 805-822.  I have tested this on multiple computers and all have the same issue.  I believe this is why so many people are complaining about VPW tables recently.

**Comment by francisdb** [comment]
JM was released with vsync override. Try setting frame pacing or no sync in the specific table settings.

**Comment by keithhov** [comment]
Thanks, I have tried those settings with most recent vpin betas, still get a big performance hit.....next I will try just the base versions of the beta without adding the files to add color,,, its the only thing else I can try.

**Comment by toxieainc** [comment]
@keithhov Could you please compare https://github.com/vpinball/pinmame/actions/runs/7434325045 with https://github.com/vpinball/pinmame/actions/runs/7439390173 if that already demonstrates the performance problem?

**Comment by keithhov** [comment]
@toxieainc 
Here are results of some testing of fishtales...... I just had back surgery to had to test on desktop (60 hz) but I have the same performance issues as cabinent pc that is 120 hertz....  I do show a difference in the 2 versions you asked me to test.   

732-No issues at anytime... stays locked in 60 FPS in any resolution(testings in 4k), any settings in F12, even with full probe settings,, CPU utilization low, GPU utilization stays below 40% and only goes up 1-2 percent when flashers hit.

734.....first time i play it after install.... no issues same as above..... problems begin after windows reboots...... first game after windows reboots and game is played in 4k>>>>>>game loads gpu utilization settings in around 40% before ball in launched,,,, ball launches, a few flashers hit durning launch and FPS immediately  drop to around 52 frames for 2-3 seconds, then back to 60 FPS but GPU and CPU  ,,,, stable at 60 FPS until center captive ball is hit, drops to 52 frames for 2-3 seconds again as a few flashers hit, then back to 60.   Frames also drop the first time ball drains on right of left,  a few lights hit but its not aggressive.... during all the frame drops CPU and GPU utilization either has no change or maybe 1 or 2 %. 

734- in 1080 resolution!!!!........ same as in 4k,  lose frames at same moments,, even though CPU utilization is very low and GPU utilization is in teens or even belows.......this is why I strongly believe there is an issue.

Going back and playing the table a second time in general with 734 I don't get the frame drops,,, but they come back every time windows boots until the 2nd/3rd time playing the table.  I thought it might be a cache issue but if i manually delete the cache in the roaming folder the table still plays smoothly as long as windows is not rebooted. 

I just quickly tested 858 and it seems to perform more like 734,(once a tables was played, no frame loss until windows reboots).....I had tested some versions in the lower 800s and those seemed to give more consistent frame drops regardless of how often it was played.

I only came across this as my cabinet shuts down at night and starts next day automaticially.... I would tweak fish tales to play great, then next day it was poor again and I was stumpled,,,, thats when i tested on multple setups and came across the same issue.

Hope this information helps,  I will likely stick with 858 if it performs well and I get good performance on my main setup on other tables....but I imagine some of the people who keep complaining about performance of VPW tables are getting the bad perfomance the first time the table is run.  

If you have any other tests that might help let me know and thanks for all you do....love this hobby.

**Comment by vbousquet** [comment]
FishTales has (long) timer script that are ran on fixed interval timer below the the framerate. This causes the stutter and in fact is the expected behavior since VPX will perform multiple time these timers per frame. For example, a script taking 0,1 ms to run but called every 1ms will hit 10% of the computer power. Here, the way the table is made, needs either a powerful enough computer, VPX to not honor the timer intervals. I would say, the solution would be to update the table and remove these timers.

**Comment by toxieainc** [comment]
@keithhov As you mentioned 'many tables', any other ones that show this behavior since 734?

**Comment by keithhov** [comment]
I ran into some performance issues in a decent amount of tables but that was more of when i updated to a version in the upper 780s I believe, i played a dozen or so tables and at least half had some studder where in the past few months i was locked in at 120 FPS.......honestly I dont know what version of vpinmame I had previously....... I will test a dozen or so later tonight with version 732 and compare to version 858 and report back with either no issues or give a few examples......I will try to do a mix of tables that are graphic/light intensive and some more basic ones...... I have a 4070 super ti so I am using a pretty powerful card.

**Comment by keithhov** [comment]
transformers--pinmame 732 with or without PWM enabled... 120 FPS consistently even when hitting double scoring with multiball......after install 858.....occasionly frame drops without PWM enbable when simple flashers hit..... big drop in frames when double scoring enabled,, drops below 90 for a few seconds.

**Comment by vbousquet** [comment]
There was an issue with the way VPX would interact with PinMame
Could you test with the latest build here (you need a github account): https://github.com/vpinball/vpinball/actions/runs/8121799622

It may have solve your performance problems

**Comment by keithhov** [comment]
@vbousquet 

Getting variable undefined 'idx' script error line 1 on just about every table for vpx908, 

Testing 907 with most recent pinmame beta now and will update soon.

**Comment by vbousquet** [comment]
Sorry, pointed you to the wrong one. The latest is this one: https://github.com/vpinball/vpinball/actions/runs/8124353244

**Comment by keithhov** [comment]
@vbousquet   909 gives script error as well.
 Runtime error-------------
Line: 1
Out of stack space: 'cb'

Originally you pointed me to 907, I am going to try 907 until you direct me to a different version

**Comment by keithhov** [comment]
@vbousquet .......vpx 907 with pmame 862......significant improvement in performance, fish tales 120 FPS in 4K at highest settings,  Johny Mnec, 120 FPS during yakuzuma strike in 4k with pwm enabled.  

Noticed left side flipper in roller coaster tycoon no longer working.

VPX did crash about 20% of the time when loading tables, but overall a big jump in performance.

**Comment by toxieainc** [comment]
@keithhov Could you please list tables that crash with the latest build?

**Comment by keithhov** [comment]
@toxieainc I haven't had any crashes since rebooting windows...... a big improvement in performance across the board on all tables.....1910 fixed script errors and fixed flipper issues on rollercoaster tycoon.  

I will post here if I come across any issues testing a few dozen tables over the next few hours.

**Comment by keithhov** [comment]
all worked great.. no more peformance issues.
