### ISSUE TITLE
Problems with lights and indicators on some tables (Family Guy)

### ISSUE THREAD

**Issue by ChaosSlave51** [vpinball/pinmame#237]
On Family Guy the Stevie Pinball lights don't work correctly. I have 100% narrowed this down to a MAME issue. 
They work right in 3.5
In the Feb 1 beta build the lights never come on.
In the current nightly build Feb 25th, some lights come on, but they are wrong. You can see at start of table how they fail to strobe correctly and instead flicker.

Some people with older builds between these two time periods report the table working correctly.  

Probably related to this is the door in drawbridge Medival Maddness doesn't get always correctly indicated to the table from the rom. 

I think this has something to do with these lights being some sort of extended list. 
![image](https://github.com/vpinball/pinmame/assets/2209573/49115bb4-0709-4a6d-8fa0-bbe0b88cef35)

**Comment by toxieainc** [comment]
Might be related to @vbousquet ' s PWM changes

**Comment by ChaosSlave51** [comment]
Most likely related to https://github.com/vpinball/pinmame/issues/226#issuecomment-1951937744

**Comment by superblobster** [comment]
In #863 the Stewie lamps come on but don't flash like they're supposed to.

**Comment by Nicals** [comment]
> Most likely related to [#226 (comment)](https://github.com/vpinball/pinmame/issues/226#issuecomment-1951937744)

I can confirm it solves this issue.
