### ISSUE TITLE
Several flasher solenoids only outputting 0 and 1 on BDK

### ISSUE THREAD

**Issue by apophis79** [vpinball/pinmame#238]
When using UseVPMModSol=2 with ROM **bdk_294** there are some flasher solenoids that are only outputting either 0 or 1. The following solenoids have the issue:

SolModCallBack(19)
SolModCallBack(23)
SolModCallBack(25)
SolModCallBack(27)
SolModCallBack(29)
SolModCallBack(32)

**Comment by vbousquet** [comment]
Fix is in this PR: https://github.com/vpinball/pinmame/pull/239

**Comment by apophis79** [comment]
I confirm this is fixed!
