### ISSUE TITLE
Anti-aliased internal alpha-segment-display rendering broken

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#240]
..since https://github.com/vpinball/pinmame/pull/194

**Comment by toxieainc** [comment]
Fixed by #cadd69c6ee0ab2cfea6017ac53b5a23e49142176

**Comment by vbousquet** [comment]
Thanks !

**Comment by toxieainc** [comment]
My solution is kinda whacky, but it seems to do the trick.  ;)

**Comment by volkenborn** [comment]
![hs_l4](https://github.com/vpinball/pinmame/assets/3236140/3d68e3a1-583b-4d73-b700-688abc08c849)

As you can see, all smaller digits are rendered with all-on segments by now.
Moreover, trying to run
>pinmame -window -dmd_compact hs_l4

will crash out with an Exception at EIP=0069CB0B: ACCESS VIOLATION while attempting to read memory at 025E6034.
I hope this is only a small issue... :/

**Comment by toxieainc** [comment]
@volkenborn I couldn't repro this, but found the most likely cause, please verify, thanks!

**Comment by volkenborn** [comment]
@toxieainc Works perfect now, thanks a lot! 👍

**Comment by toxieainc** [comment]
@volkenborn I did 2 more improvements, please test again at some point, thanks!!
