### ISSUE TITLE
Add build number and SHA7 to the file properties

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/pinmame#241]
Similar to this issue on vpinball: https://github.com/vpinball/vpinball/issues/1530

Is your feature request related to a problem? Please describe.
When testing a lot of builds from the actions and you do not know anymore which version did you just install.

Describe the solution you'd like
If the build number and SHA7 is added to the file properties, it is just a right click away.

Describe alternatives you've considered
Alternative solution would be to name the VPinball.exe with the version and build included in the name

Additional context
I tested it on a fork (on vpinball):

![image](https://github.com/vpinball/vpinball/assets/12571104/93cb9858-e285-46d4-823a-a4f4a7aba3a7)

build number included in the File version and build number and SHA7 included in the Product version

**Comment by toxieainc** [comment]
Solved by #245 , thanks!
