### ISSUE TITLE
New Atari roms available at VPU that have been hacked for freeplay

### ISSUE THREAD

**Issue by CarnyPriest** [vpinball/pinmame#253]
VPU member empee3 has been submitting Atari roms that he has patched for freeplay. I propose adding them to the source:

https://vpuniverse.com/files/file/18960-atari-space-riders-1978-freeplay-rom/

https://vpuniverse.com/files/file/19060-atari-middle-earth-1978-freeplay-rom/

**Comment by volkenborn** [comment]
I just dropped him this message:

> I just tried your Space Riders freeplay ROM, and it works,
> but when I want to start a two-player game, the 3rd player display shows "07".
> 
> The same happens when a four-player game is started (the "00" on 3rd player display is replaced by "07" again).
> Scoring during the game seems unaffected though.
> 
> This issue does not occur when running the Middle Earth free play ROM.
> Can you veryfy this on a real machine?

**Comment by tromop** [comment]
Attached is the freeplay rom version for Atari Airborne Avenger (1977) i've made
[aavenger.zip](https://github.com/vpinball/pinmame/files/14642549/aavenger.zip)
Grtx,
Onno

**Comment by tromop** [comment]
Attached is the freeplay rom version for Atari Middle Earth (1978) i've made
[midearth.zip](https://github.com/vpinball/pinmame/files/14642571/midearth.zip)
Grtx,
Onno

**Comment by tromop** [comment]
Attached is freeplay rom version for Atari Middle Earth (1978) i've made
[midearth.zip](https://github.com/vpinball/pinmame/files/14642854/midearth.zip)
Grtx,
Onno

**Comment by toxieainc** [comment]
Thanks, will add these, too!

**Comment by tromop** [comment]
Attached is the freeplay rom version for Atari The Atarians (1976) i've done
[atarians.zip](https://github.com/vpinball/pinmame/files/14673109/atarians.zip)
Grtx,
Onno

**Comment by toxieainc** [comment]
Thanks!

**Comment by tromop** [comment]
Attached is the freeplay rom version for Atari Time 2000 (1977) i've done.
[time2000.zip](https://github.com/vpinball/pinmame/files/14727236/time2000.zip)
Have (pinball) fun,
Onno
ps. Now all Atari Generation 1 systems available have a freeplay version

**Comment by toxieainc** [comment]
Great, thanks, will also add that one!
