### ISSUE TITLE
AltSound: Only first audio file played in 3.6-822 (jupk_513)

### ISSUE THREAD

**Issue by gitskyflux** [vpinball/pinmame#259]
Altsound test files: Jurassic Park 5.13, jupk_513
Altsound Mode 1
Everything works correctly in 3.6-369.
Upgraded to 3.6-822 and only the first audio file (T-Rex) is heard.
Altsound.log indicates files are being loaded and played on the channel(s) correctly, but there's no sound.
After moving back to 3.6-369, sound is heard.

I also tested with Simpson's Pinball Party, but from what I can tell those are working correctly in both versions.

**Comment by toxieainc** [comment]
@droscoe may be able to help here

**Comment by droscoe** [comment]
> Altsound test files: Jurassic Park 5.13, jupk_513 Altsound Mode 1 Everything works correctly in 3.6-369. Upgraded to 3.6-822 and only the first audio file (T-Rex) is heard. Altsound.log indicates files are being loaded and played on the channel(s) correctly, but there's no sound. After moving back to 3.6-369, sound is heard.
> 
> I also tested with Simpson's Pinball Party, but from what I can tell those are working correctly in both versions.

Are you on discord?  I prefer to debug issue more interactively.  My username is mrgrynch on Discord.

**Comment by gitskyflux** [comment]
I assumed I wouldn't be the only one experiencing this as it seemed straightforward especially when confirming a different rom/altsound combo works as expected. My intention was to simply report it for the community's sake. I won't be able to get back to this for several more days, so you can close this one if you want. It's not important to me personally.

**Comment by toxieainc** [comment]
No, all good. We need reports like these, thanks!

**Comment by droscoe** [comment]
> I assumed I wouldn't be the only one experiencing this as it seemed straightforward especially when confirming a different rom/altsound combo works as expected. My intention was to simply report it for the community's sake. I won't be able to get back to this for several more days, so you can close this one if you want. It's not important to me personally.

I will try to reproduce this.

**Comment by droscoe** [comment]
I just ran this table with the latest pre-release version of VPinMAME and everything worked fine.  I will try the specific version you mentioned in your original issue

**Comment by droscoe** [comment]
I just ran the game with the 822 release and it ran fine.  I did not experience the problem reported.  This test was performed with 64-bit.  Are you running 32-bit @gitskyflux ?

**Comment by gitskyflux** [comment]
I was on 64-bit. I will try again with the 929 release, but go ahead and close as needed since this sounds isolated.

**Comment by droscoe** [comment]
> I was on 64-bit. I will try again with the 929 release, but go ahead and close as needed since this sounds isolated.

I'd be willing to work with you to try and figure out why it behaves this way in your setup.  It is possible that there is a bug that is revealed in your specific environment.
