### ISSUE TITLE
ColourRom for StarTrek LE (st_161hc) dosen´t work with VPinMAME-3.6.0-906-9440f77

### ISSUE THREAD

**Issue by surroundfreak** [vpinball/pinmame#260]
hi,
i had written here:
https://vpuniverse.com/files/file/18211-alien-star-gottlieb-1984/page/2/?tab=comments#comment-65138

"With the new VPX 10.8RC2-Version the sounds are all correct on my computer. With the new VPinMAME-Version, your table had no problems, but with this new VPinMAME-Version the Colour-ROM for StarTrek LE (st_161hc i think) dosen´t work anymore for example. I get the error "Game not found". Thats pity..I had copy back the dll from an old VPinMAME version. Now i can play your table and the colourRom from ST LE."

br surround

**Comment by toxieainc** [comment]
You need to download the "sc" variant in the downloads/actions..

**Comment by surroundfreak** [comment]
> You need to download the "sc" variant in the downloads/actions..

Thank you :-) Can you tell me, what is the different between both versions?

**Comment by toxieainc** [comment]
The 'sc' one has these additional/artificial color rom slots.

**Comment by surroundfreak** [comment]
Thank you again. I download the "sc"-Version.. Nice week for you!
