### ISSUE TITLE
Make sure the "volume" value in the game options registry can handle positive integers.

### ISSUE THREAD

**Issue by Panasony1008** [vpinball/pinmame#264]
The registry value for "volume" is only valid from -32 to 0.
Just change one line, You can now handle positive values.
Solve the problem of tables with low volume and difficult to adjust.
I think it will be helpful for everyone, so could you please fix it?

**<src\windows\config.c>
{ "volume", "vol", rc_int, &attenuation, "0", -32, 0, NULL, "volume (range [-32,0])" },
　=>　{ "volume", "vol", rc_int, &attenuation, "0", -32, 32, NULL, "volume (range [-32,32])" },**

You can set the volume directly by editing the registry or using a VPX script.
.Games(cGameName).Settings.Value("volume") = int_val

Ideally, it would be nice to have "volume" added to the game options menu.

**Comment by Panasony1008** [comment]
I created a version that can save volume settings based on VPinMAME-sc-3.6.0.

_https://mega.nz/folder/ZTt2kYxC#4LWfwrNWteLGephEaZBhGg_

The volume adjusted with the OSD menu master volume (”TILDE" or "TAB" key on MameDMD) can be saved for each ROM.
Effective for tables where VPinMame's sound is small.

Note
After adjusting the master volume in the OSD menu, click "OK" in the "F1" Mame menu to save.
You can set the volume directly by editing the registry or using a VPX script.

_.Games(cGameName).Settings.Value("volume") = "Val"_

"Val" is an integer between -32 and 32, and the unit is db.
Registry for each Rom of vpinmame(default is also valid)

_KEY_CURRENT_USER\SOFTWARE\Freeware\Visual PinMame\\<Rom Name\>\volume_

**Comment by toxieainc** [comment]
Thanks, will checkout the source and try to commit it.

**Comment by Panasony1008** [comment]
please.
I also enable the OSD with the TAB key.
This is because keyboards in my country do not have a tilde key.
I don't think there is any harm since the TAB key is probably not used in vpinmame.
GameOption's registry save specifications have also been changed so that it is saved with OK.

**Comment by toxieainc** [comment]
I slightly tweaked your patch, but it should work as before, but please retest. Note that i did not include the TAB key change, as its already employed.
Any other key that would be okay for ppl without tilde keys?

**Comment by Panasony1008** [comment]
I confirmed the operation.
very good.
Regarding the OSD open key, ideally the "KANJI" key would be good, but can I use the "o" key?

**Comment by Panasony1008** [comment]
This is a suggestion for an alternative key since the Japanese keyboard does not have a TILDE key.
What about the Japanese keyboard's unique YEN key so it doesn't affect other keys?
You need to add a definition for the YEN key.

src\windows\input.c　Add
	{ KEYCODE_YEN, 			DIK_YEN , 			'\\'	,		'\\' },

src\input.h　Add to enum
	KEYCODE_YEN,

src\inptport.c　change
	{ IPT_UI_ON_SCREEN_DISPLAY, "On Screen Display",	SEQ_DEF_3(KEYCODE_TILDE, CODE_OR, KEYCODE_YEN) },

[src.zip](https://github.com/vpinball/pinmame/files/14973026/src.zip)

**Comment by toxieainc** [comment]
Sounds good, will add it right away.
