### ISSUE TITLE
Compile issues with GCC14

### ISSUE THREAD

**Issue by 6wl** [vpinball/pinmame#265]
gcc (GCC) 14.0.1

Looks like changes to GCC14 have created a few compile errors with the default CFLAGS now.
https://discourse.nixos.org/t/rfc-more-c-errors-by-default-in-gcc-14/27390

Eg
src/sound/streams.c:253:81: error: passing argument 2 of ‘stream_callback_multi[channel]’ from incompatible pointer type [-Wincompatible-pointer-types]

**Comment by toxieainc** [comment]
Would you have a complete log of the compile errors please, so that i could fix these without having to setup a complete setup?

**Comment by 6wl** [comment]
So this is using the linux-x64 CMakeList file.  Looks to be just the 1 file, but 2 errors from streams.c
[error.txt](https://github.com/vpinball/pinmame/files/15016897/error.txt)
