### ISSUE TITLE
GI String B2S communications are messed up when UseVPMModSol = 2

### ISSUE THREAD

**Issue by apophis79** [vpinball/pinmame#267]
**Describe the bug**
When setting UseVPMModSol = 2 on some tables (specifically RBION in this example) and then inspecting signals sent to B2S server using the "All ID in 1 Visual B2S" backglass reveals some strange behavior in the Solenoids and GI String signals. Also, occasionally causes errors.

**To Reproduce**
1. Download this unreleased RBION VPX file that uses new PWM effects: https://drive.google.com/file/d/1EY3p2auNOSVPut9c9Q8SAPoNYmxnzkAX/view?usp=sharing
2. Download this B2S file: https://vpuniverse.com/files/file/4829-all-id-in-1-visual-b2s/
3. Rename the B2S file to same name as the VPX file, the run the table.
4. Observe strange GI string signals. See screenshot 1 below
5. Intermittently an error will pop up. See screenshot 2 below

**Expected behavior**
Screenshot 3 below is what we expect to see.
You will see this if you run the released version of the table: https://vpuniverse.com/files/file/18488-ripleys-believe-it-or-not-stern-2004-vpw-mod/

**Screenshots**
Screenshot 1
![image](https://github.com/vpinball/pinmame/assets/74864015/1170c789-cf72-42d2-a966-84cc2b3f4ba0)

Screenshot 2
![image](https://github.com/vpinball/pinmame/assets/74864015/9d2427d4-a9a9-4d6b-8913-da56fed12662)

Screenshot 3
![image](https://github.com/vpinball/pinmame/assets/74864015/1cab7970-c546-498e-a483-18061db569d4)

**Versions & Settings**
 - VPinMame v3.6.0-929-8c5f83e
 - VPX: v10.8.0 Beta (Rev 1947 (3b3f101), windows DirectX 64bits)
 - Windows 11

**Additional context**
I know this also happens on Safe Cracker and Stern Spiderman. It like is an issue on many tables.

**Comment by vbousquet** [comment]
Issue has been pushed to B2S with solution. @toxieainc This one can be closed

**Comment by toxieainc** [comment]
Thanks!
