### ISSUE TITLE
All stern roms have issues with VPinMame versions 947 and 948 fixing AFM bugs

### ISSUE THREAD

**Issue by ironhunter81** [vpinball/pinmame#271]
The games start and you can play but neither the lights nor the toys work
I tested Big Buck Hunter pro
Family Guy and Shrek

**Comment by Willybits** [comment]
confirmed on v347

**Comment by lminimart** [comment]
The mentioned tables DO seem affected... but not Star Trek (2013)?

**Comment by ironhunter81** [comment]
> The mentioned tables DO seem affected... but not Star Trek (2013)?

I only tried those three
then I went back to a previous version, even if it has the UFO bug on afm but for the moment I prefer what it is

**Comment by lminimart** [comment]
Just pointing it out in case it's a helpful data point for @vbousquet & co!

**Comment by Loadedweapon** [comment]
Yes Dark Knight is broken.. No lights
