### ISSUE TITLE
Some Gottlieb tables no longer work.

### ISSUE THREAD

**Issue by GHOSTfaceKILLr1974** [vpinball/pinmame#274]
I'm update to vp 10.8.0 rc3 and vpinmame 3.6.0-967-64d4446 (32bit and 64bit).

Buck Rogers
Charlies Angels
Close Encounters
Dragon
Genie
Joker Poker
The incredible Hulk

Is this a rom issue or is this a script issue?

**Comment by gdycaps24680** [comment]
https://github.com/vpinball/pinmame/issues/273

**Comment by GHOSTfaceKILLr1974** [comment]
Split a bin file?


> #273

Thanks. I got everything but splitting the downloaded .bin file is beyond me.

**Comment by Karl030167** [comment]
just look out for the fixed roms... maybe at VPF
can be closed...

**Comment by gdycaps24680** [comment]
I'm also uncertain about how to split the bin file.  My best guess is if
you have access to Linux, you can use the split command to do it.  In any
case, I imagine the proper roms will show up on VPU at some point.

**Comment by Spacegoogie** [comment]
I know this is old, I just started The incredible Hulk and I get a script error.
Any fix?

**Comment by Karl030167** [comment]
The fix should be to use the new/modified Gottlieb roms

**Comment by francisdb** [comment]
> I know this is old, I just started The incredible Hulk and I get a script error. Any fix?

What script error?
Got a table link?
What rom are you using?
