### ISSUE TITLE
Sound and dmd stutter with last build

### ISSUE THREAD

**Issue by christobal03** [vpinball/pinmame#276]
Hello, since the last update, some slowdown/stuttering appears on certain tables in terms of audio and dmd, which completely freezes the table for a few seconds.

An example with AFM : 

https://github.com/vpinball/pinmame/assets/171031555/f10e102a-5969-4109-a5d5-7c2bd29be3af

**Comment by gdycaps24680** [comment]
Which version exactly?  Are you running one of the experimental builds?

https://github.com/vpinball/pinmame/issues/268

**Comment by bernarma** [comment]
I get a similar problem but not as exaggerated as what you are noticing. I am running 3.6.0-929-8c5f83e (64-bit version). I am also running the 10.8.0-1947-3b3f101 and the Backglass Server is 2.1.1.

**Comment by vbousquet** [comment]
This should be better (fixed ?) in latest that is to say VPinMame 973: https://github.com/vpinball/pinmame/actions/runs/9329924126 and VPX 1955: https://github.com/vpinball/vpinball/actions/runs/9324333326

**Comment by bernarma** [comment]
> This should be better (fixed ?) in latest that is to say VPinMame 973: https://github.com/vpinball/pinmame/actions/runs/9329924126 and VPX 1955: https://github.com/vpinball/vpinball/actions/runs/9324333326

I'll update and let you know if I experience the problem. Thanks for the quick reply - I usually suffer in silence but this time I thought I might check if someone else has reported the issue and sure enough there was something raised. Stay tuned - it should take me a few days to try and replicate or confirm if I don't experience the problem anymore.

**Comment by bernarma** [comment]
> This should be better (fixed ?) in latest that is to say VPinMame 973: https://github.com/vpinball/pinmame/actions/runs/9329924126 and VPX 1955: https://github.com/vpinball/vpinball/actions/runs/9324333326

I don't see that issue anymore (or so I believe). I'll keep playing but I think the later versions you recommended have resolved the issue. It is very much appreciated @vbousquet and team.

**Comment by lminimart** [comment]
Just a side note.... it seems like even with these new builds that fix the Bally/Williams stutter issues, the Capcom roms seem to still have something similar going on. Noticing it while playing the new VPW Breakshot.

**Comment by LunatechFringe** [comment]
I'm having audio and DMD stuttering issues with the Gedankekojote97 build of FunHouse using ROM fh_905h.

**Comment by vbousquet** [comment]
This issue has been identified and fixed since the initial report, therefore I will close it.
Please tell us if you're still having issues with this
