### ISSUE TITLE
libpinmame fails to link with current master

### ISSUE THREAD

**Issue by mkalkbrenner** [vpinball/pinmame#279]
``
/usr/bin/ld: libpinmame.so.3.6: undefined reference to `core_update_pwm_outputs(int, int)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/pinmame_test.dir/build.make:99: pinmame_test] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/pinmame_test.dir/all] Fehler 2
```

**Comment by mkalkbrenner** [comment]
going back to [74040732a4ab209edfcbaaee79d73d6608456da6](https://github.com/vpinball/pinmame/commit/74040732a4ab209edfcbaaee79d73d6608456da6) solves the issue for PPUC

**Comment by vbousquet** [comment]
I just had a look and I don't get why this is not linking. The reported missing symbol is defined and exported in core.h. Beside it is also used by VPinMame controller and standalone and as far as I can tell it works seamlessly there. Is there anything special in PPUC build ?

@jsm174 Any clue on this ? Does it build as expected for standalone ? Did you have anything to tweak for it ?

**Comment by jsm174** [comment]
I've had some conversations with @mkalkbrenner over Discord.

I'm at a loss too. Were compiling fine in the CI, and it's working in standalone.

**Comment by mkalkbrenner** [comment]
I think I found the issue. It is not related to pinmame.
It is caused by the external.sh scripts we use in VPX Standalone and PPUC. You can set the SHA of an external dependency to master or main. But since we have caching based on the SHAs, it will never update an external dependency anymore if it is "master". So previously you always got the latest pinmame on each build by setting the SHA to "master". Now, with caching, it is the opposite. 🤦

**Comment by jsm174** [comment]
Re-opening.

This can now be reproduced on linux-x64. Simply building it in `Debug` mode will cause the 

```[ 99%] Building CXX object CMakeFiles/pinmame_test.dir/src/libpinmame/test.cpp.o
[100%] Linking CXX executable pinmame_test
/usr/bin/ld: libpinmame.so.3.6: undefined reference to `core_update_pwm_outputs(int, int)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/pinmame_test.dir/build.make:99: pinmame_test] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/pinmame_test.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

Working:

```
git clone https://github.com/vpinball/pinmame
cd pinmame
cp cmake/libpinmame/CMakeLists_linux-x64.txt CMakeLists.txt
cmake -DCMAKE_BUILD_TYPE=Release -B build
cmake --build build -- -j20
```

Failing:

```
git clone https://github.com/vpinball/pinmame
cd pinmame
cp cmake/libpinmame/CMakeLists_linux-x64.txt CMakeLists.txt
cmake -DCMAKE_BUILD_TYPE=Debug -B build
cmake --build build -- -j20
```

**Comment by jsm174** [comment]
I narrowed it down to the `INLINE's` in `core.h`. If I comment out the calls `core_update_pwm_outputs` everything compiles.

```
extern void core_update_pwm_outputs(const int startIndex, const int count);
INLINE void core_update_pwm_gis() { /*if (options.usemodsol & (CORE_MODOUT_FORCE_ON | CORE_MODOUT_ENABLE_PHYSOUT_GI)) core_update_pwm_outputs(CORE_MODOUT_GI0, coreGlobals.nGI);*/ }
INLINE void core_update_pwm_solenoids() { /*if (options.usemodsol & (CORE_MODOUT_FORCE_ON | CORE_MODOUT_ENABLE_PHYSOUT_SOLENOIDS | CORE_MODOUT_ENABLE_MODSOL)) core_update_pwm_outputs(CORE_MODOUT_SOL0, coreGlobals.nSolenoids); */}
INLINE void core_update_pwm_segments() { /*if (options.usemodsol & (CORE_MODOUT_FORCE_ON | CORE_MODOUT_ENABLE_PHYSOUT_ALPHASEGS)) core_update_pwm_outputs(CORE_MODOUT_SEG0, coreGlobals.nAlphaSegs);*/ }
INLINE void core_update_pwm_lamps() { /*if (options.usemodsol & (CORE_MODOUT_FORCE_ON | CORE_MODOUT_ENABLE_PHYSOUT_LAMPS)) core_update_pwm_outputs(CORE_MODOUT_LAMP0, coreGlobals.nLamps);*/ }
```

I'll keep researching, but somehow in debug mode on linux, `INLINE` must be treated different

**Comment by jsm174** [comment]
I think removing 

`INLINE=static __inline__`

and switching to what we do in the macos cmakes seems to work:

`add_definitions( "-DINLINE=static inline __attribute__((always_inline))" )`

@toxieainc, @vbousquet - Any negative side effects if we do this?

**Comment by toxieainc** [comment]
It could be a bit faster this way even, but nowadays this is hard to generalize as processor architectures differ so much.
It may compile a bit longer this way, as more functions will be inlined.
