### ISSUE TITLE
Wheel of Fortune misses small display LEDs

### ISSUE THREAD

**Issue by toxieainc** [vpinball/pinmame#292]
@vbousquet I just tested WOF, and the small display LEDs do not show up anymore in the VPX tables, most likely since the new PWM code was introduced (only checked some builds i had still lying around).

**Comment by Karl030167** [comment]
tried with ninuzzus and bigus1 versions. I "bugfixed" it with this :  
its on layer 8, select whole led array, change Intensity to 100

**Comment by toxieainc** [comment]
Thanks, thats a good hint on where to search for.

**Comment by vbousquet** [comment]
This one is expected as this is a hack we put to let existing table runs. It is documented in the code: https://github.com/vpinball/pinmame/blob/01f2bbbe0283ff47ba8af5a9f8a3e1407690aa27/src/wpc/vpintf.c#L109

The table has been updated (and FG/Shrek may already be updated or will shortly) so maybe we should just remove this hack ?

**Comment by toxieainc** [comment]
Out of interest: Where are these LEDs on FG and Shrek?
Cause from my testing, for WOF we could remove this hack already for the existing table (and its variants/MODs).

**Comment by vbousquet** [comment]
I may be wrong but as far as I remember, these are the mini playfield led PCB

**Comment by toxieainc** [comment]
Thanks!
For WOF i changed the behavior already, as the existing table(s) work like that again.
For FG and Shrek, i'll leave that up to you then.

**Comment by toxieainc** [comment]
..i also just changed FG and Shrek.
The existing tables do not cope with it optimally, but at least partially work, so maybe a good tradeoff going forward..
