### ISSUE TITLE
Gottlieb Sys1 games will no longer run (Error rom file or rom path)

### ISSUE THREAD

**Issue by multigametechniek** [vpinball/pinmame#294]
On my setup, Gottlieb system 1 games like Totem, Asteroid Annie, Countdown etc. will no longer successfully run after updating to 
 v3.6.0-998-a77c2d2 (64bit).
They all give an error regarding rom file or rom path.
Going back to vpinmame v3.6.0-929-8c5f83e (64bit) and works fine again.
VPX version 10.8.RC4
Windows 10 Pro

**Comment by volkenborn** [comment]
That's because one of the Gottlieb System 1 base ROMs was  misdumped.
Too bad it was discovered really late, when the ROMs were redumped in 2023.
Sorry for this inconvinience but you're goona need the new dumps.
