### ISSUE TITLE
The GI string light intensities in Metallica are too low when UseVPMModSol = 2

### ISSUE THREAD

**Issue by apophis79** [vpinball/pinmame#312]
**Describe the bug**
The GI strings in Metallica are driven using lamp matrix indexes 130, 132, 134, and 136. When using new PWM functionality for the lamp matrix (UseVPMModSol = 2) the maximum intensity of the GI strings is very low (approx 20% of max). To solve this issue, I had to multiply the resulting PWM values coming from VPinMame for these lights by a factor of 5. 

**To Reproduce**
1. Download the table at this link (I will need to give you access, so please request access): https://drive.google.com/file/d/1SaIN1QB_dxxgdogCGAPziFIlqPQpP_jS/view?usp=drive_link
2. Download the ROM at this link: https://drive.google.com/file/d/1wYtYMJVI4G-jAI-0W3ZdHTfp_MaNCQ_9/view?usp=sharing
3. Search in the script for `Const GIScale` and set it to a value of 1.
4. Notice the GI lights are always very dim. Setting the GIScale back to 5 makes use the full brightness range.

**Expected behavior**
The GI Strings PWM signals should not need to be manually manipulated in the script to work correctly. 

**Versions & Settings**
VPinMame: 3.6.0.1038
VPX: v10.8.0 Beta Rev 1995 (a491317) windows directX 64bits
Windows 11

**Comment by vbousquet** [comment]
This issue is very likely linked to https://github.com/vpinball/pinmame/issues/311
Metalica uses the grinder nodeboard (part 520-5331-00) which is not fully emulated. We would need the firmware of this board or spend a significant amount of time reverse engineering the main CPU board to go further.

**Comment by apophis79** [comment]
Note, I removed the table link in my original post above. You can just download the latest version of VPW's Metallica from VPUniverse.

**Comment by apophis79** [comment]
Thank you!
