### ISSUE TITLE
Gottlieb System 1 issues

### ISSUE THREAD

**Issue by lminimart** [vpinball/pinmame#317]
![image](https://github.com/user-attachments/assets/a72dd308-a187-452a-87d6-c3ee1e1fc2ec)
Here's a list of Gottlieb System 1 games. Every one of these tables I've tested so far with both the most recent release of Vpinmame and the latest build from actions has one of the following two issues:

1) There's a "terminated before initialization" error and the game doesn't load (Cleopatra, Torch, Totem):

![image](https://github.com/user-attachments/assets/05411eae-9d60-4bfe-a208-695f6160ab35)

2) The game will load but a game cannot be started (Charlie's Angels, Count-Down).

EDIT: when testing from within Vpinmame (3.6.0.1081.12733ae) itself, every one of those Gottliebs returns this error:

![image](https://github.com/user-attachments/assets/8ab477d3-e160-457a-aabe-03bb67c7b2c2)

**Comment by gdycaps24680** [comment]
https://github.com/vpinball/pinmame/issues/273

**Comment by lminimart** [comment]
Ah, sorry... did not know about the new roms! They do indeed fix the issue. Closing.
