### ISSUE TITLE
Al's Garage Band, DMD blocks and table crashes.

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/pinmame#324]
DMD works until version VPinMame 3.6.1082.  Other newer versions, the DMD doesn't work because it blocks and the table crashes.
Using MSI 4K laptop and NVIDIA RTX 3080ti. Desktop version.

**Comment by vbousquet** [comment]
I have updated this part. Could you give it a go and see if it's ok for you ?
If not, could you share all your setup information: VPX and which version ? using Freezy's DMD and which version ? using colorization with which setup ? ...

**Comment by JorgePedro65** [comment]
Now it's alright, it works again. Thank you so much Vincent.
