### ISSUE TITLE
DMD brightness is low (Pistol Poker)

### ISSUE THREAD

**Issue by GHOSTfaceKILLr1974** [vpinball/pinmame#332]
I'm on VPX 10.8.0 beta (Rev. 1985 (c517981) 64bit) and Vpinmame 3.6.0.1104.064b52f (64bit).

DMD brightness is low for Alvin G. & Co. Pistol Poker.
Try to increase brightness for only "pstlpkr" but it seems to only save globally causing every other tables dmd to be way to bright.

**Comment by francisdb** [comment]
Same issue with Street Fighter II here, my external dmd is very dim compared to other tables.

**Comment by toxieainc** [comment]
@vbousquet for vis

**Comment by francisdb** [comment]
Pistol Poker indeed fixed. Street Fighter II not. Want me to create a new issue?

**Comment by francisdb** [comment]
I can confirm it's a general GTS3 issue as I also see it on Waterworld and Barb Wire.

**Comment by vbousquet** [comment]
> Pistol Poker indeed fixed. Street Fighter II not. Want me to create a new issue?

Yes a new issue with the exactly used versions would help (since I can't reproduce on Windows / Freezy / ...)

**Comment by GHOSTfaceKILLr1974** [comment]
> Pistol Poker indeed fixed. Street Fighter II not. Want me to create a new issue?

DMD brightness for Pistol Poker is resolved.
Thanks!
