### ISSUE TITLE
buckrgrs fails to load -- CRC has changed out from under me

### ISSUE THREAD

**Issue by gorgatron1** [vpinball/pinmame#333]
I recently upgraded to the latest vpinmame (3.6.0-998-a77c2d2) and noticed a couple of games that used to work no longer work.  For example Buck Rogers (`buckrgrs.zip`).  I get a message saying that the game failed to initiaize, so I ran the tester in Setup64 and sure enough there is a file missing: `A1752CF.bin`

It looks like it is probably down to this change from about 4 months ago:

```
- GTS1_2_ROMSTART(name, "u5_cf.bin", CRC(e0d4b405) SHA1(17aadd79c0dcbb336aadd5d203bc6ca866492345), \
-                      "u4_ce.bin", CRC(4cd312dd) SHA1(31245daa9972ef8652caee69986585bb8239e86e))

+ GTS1_2_ROMSTART(name, "A1752CF.bin", CRC(614a3bd9) SHA1(febca18fb6f96037ca82e515dd161dfcb0e4c776), \
+                      "A1753CE.bin", CRC(4cd312dd) SHA1(31245daa9972ef8652caee69986585bb8239e86e))
```

https://github.com/vpinball/pinmame/commit/24d434aca43fe15624a910707bfd0955eab37f39#diff-55ee260d7678667b42ca8dd5c4727c08579b8c05630ea261c95ae5f5c2ec2e8aL21

My filenames match the `u5_cf.bin` but I think it is actually matching on the CRC and now my u5 doesn't have the right CRC.

What is the proper way to handle this?  Is there a way to have it accept the old files (that I have)?  Or do I need to find replacements (which I have been unable to do so far)?  Is there a way to know all the files that are missing?

Thanks!

**Comment by gorgatron1** [comment]
Sooo, I think I figured this out -- please let me know if this is right:

- I remove the u5/u4 files from the buckrgrs.zip
- I create a new gts1.zip using files with the _new_ crc/sha1 (which I found by searching by crc)
- vpinmame now finds the files in gts1.zip
- I repeat the first step (removing the u5/u4 files) from every zip that contains those

**Comment by 3d2000s10** [comment]
The first and last steps should not be necessary, as long as you have the correct (updated) gts1.zip.

(unless you want to clean up unnecessary files)
