### ISSUE TITLE
External DMD (dll) displays incorrectly on some Gottliebs

### ISSUE THREAD

**Issue by Kraken74** [vpinball/pinmame#334]
Some Gottlieb tables are displaying the External DMDs incorrectly.  It looks like once a LCD segment has been lit during gameplay, it remains lit, eventually ending up with all segments lit as your score increases.  Tested with 998 and 1108.  These are used to trigger colorizations.

Some samples:

### Gottlieb System 1

Asteroid Annie
![image](https://github.com/user-attachments/assets/7a2d0436-a222-46b0-a52b-98242bbb875e)

Incredible Hulk
![image](https://github.com/user-attachments/assets/ecd700e8-e90c-49a6-a27b-d4149b91beb6)

### Gottlieb System 80

Black Hole
![image](https://github.com/user-attachments/assets/bcfce067-9daa-44c8-bd5f-025aa6ed626a)

Haunted House
![image](https://github.com/user-attachments/assets/7ca359b3-b46f-4cf1-b5dc-0dcc22a7cb1a)

Thanks!

**Comment by Kraken74** [comment]
Just tested two System 80A tables (Qbert and Alien Star) and a System 80B table (Bounty  Hunter) and they work fine, so it seems to be with specific generations.

**Comment by toxieainc** [comment]
@vbousquet Could this be due to the dimming changes?

**Comment by RenewedFire** [comment]
![image_2024-10-25_104144862](https://github.com/user-attachments/assets/664c4b7d-efa2-42cf-ba40-66a7b3c4b80e)

Also displaying incorrectly on Teed Off

**Comment by vbousquet** [comment]
> Also displaying incorrectly on Teed Off

Not sure to understand what is not displaying correctly here (previous report was regarding alphanumeric display). COuld you be more precise ?

**Comment by RenewedFire** [comment]
External DMD displaying all black outside of score, none of the dimmed pixels appear.  In gameplay, causes flashing.

**Comment by vbousquet** [comment]
> External DMD displaying all black outside of score, none of the dimmed pixels appear. In gameplay, causes flashing.

Then, this should be a different bug, that will normally be solved by https://github.com/vpinball/pinmame/pull/353

**Comment by vbousquet** [comment]
This is not a bug in PinMame but in DmdExt.
@freezy There is a Clear missing here: https://github.com/freezy/dmd-extensions/blob/b0835858bdc31f464044f04f9bbe6fcd1bddf794/LibDmd/DmdDevice/AlphaNumeric.cs#L345

**Comment by freezy** [comment]
Thanks @toxieainc for the PR!
