### ISSUE TITLE
Some issue displaying CRz altcolors

### ISSUE THREAD

**Issue by Dicentim974** [vpinball/pinmame#335]
Hi,
I've just installed the [VPinMAME-sc-3.6.0-1108-81f27e7-win-x64]
I've noticed some display issue on Creature of the black lagoon (CrZ altcolor).
Went back to [VPinMAME-sc-3.6.0-998-a77c2d2-win-x64.zip] prerelease and it's back to normal.
Thanks for all your fantastic work !

**Comment by vbousquet** [comment]
This is the same issue as https://github.com/vpinball/pinmame/issues/337

**Comment by vbousquet** [comment]
This should be solved now. Could you confirm we can close this issue ?

**Comment by Dicentim974** [comment]
> This should be solved now. Could you confirm we can close this issue ?

Hi, I can confirm : all is back to normal, it works perfectly ! Merci Vincent !
