### ISSUE TITLE
Fish Tales DMD goes blank while calculating bonuses

### ISSUE THREAD

**Issue by hotelvictorcharlie** [vpinball/pinmame#337]
On Fish Tales, the DMD goes blank for a few seconds every time a ball drains (when it's supposed to be counting up the bonuses, i.e. fish caught, tales told, etc.).

I am on version [3.6.0.1105.1a2f0a1](https://github.com/vpinball/pinmame/commit/1a2f0a14cd6edd76d579552e009b5d49811d495f).

Thanks for all that you do.

**Comment by vbousquet** [comment]
This should be solved now. Could you confirm we can close this issue ?

**Comment by vbousquet** [comment]
Closed, as confirmed here https://github.com/vpinball/pinmame/issues/335

**Comment by hotelvictorcharlie** [comment]
I can confirm that this is fixed on version 3.6.0-1110-145a527. Thank you again for addressing this so quickly!
