### ISSUE TITLE
REQ: add recent code additions from slochar / Idleman

### ISSUE THREAD

**Issue by CarnyPriest** [vpinball/pinmame#347]
https://tsqmadness.com/slochar/ZIP/

Specifically,

Ali rev. 85
Cheetah rev. 84 (PROTOSOUNDS)
Dragonfist version 15
Dragonfist version 16
Quicksilver rev. 081
Seawitch (MOD rev. 9)
Seawitch (MOD rev. 9.3)
Stars 103

Regards,
CarnyPriest

**Comment by redbone75** [comment]
How long does it generally take to get these rom revision requests in pinmame?  I'm specifically interested in Dragonfist version 16.  Thanks!

**Comment by toxieainc** [comment]
Thanks a lot for the heads up! Much appreciated!!
@redbone75 I hope to be able to look into this later today.

**Comment by toxieainc** [comment]
@CarnyPriest Do you know what this nugent-lectro-chimes.zip is about?

**Comment by toxieainc** [comment]
Next actions build will have all of the above, thanks again!!
