### ISSUE TITLE
What means '-md' in pinmame file versions

### ISSUE THREAD

**Issue by maartenlangeveld** [vpinball/pinmame#352]
What means '-md-' in pinmama file versions e.g. [PinMAME32**-md-**3.6.0-1122-79a301d-win-x64.zip] ?
Have sought everywhere but could not find what it means and in what way these version differs from the others.

**Comment by francisdb** [comment]
The answer is in the build definitions:

https://github.com/vpinball/pinmame/blob/7398e23eabdecd069f4f8bc47a2a9a42746019c9/.github/workflows/pinmame32.yml#L58-L61

**Comment by maartenlangeveld** [comment]
@francisdb Thanks! Good to know.

**Comment by jsm174** [comment]
I don't think these are technically debug builds. I think it turns on the mame debugger which makes a gui like this:

![image](https://github.com/user-attachments/assets/11282ba0-7201-4739-a2e9-1f50d486fcce)

**Comment by toxieainc** [comment]
Exactly this. So it was created e.g. to help the T2 and STTNG ROM MOD developers, as they use that feature.
