### ISSUE TITLE
REQ: add Batman Forever unofficial mod v5.00 from PinballCodes.com

### ISSUE THREAD

**Issue by CarnyPriest** [vpinball/pinmame#356]
https://www.pinballcode.com/bmf500

**Comment by toxieainc** [comment]
Thanks!

**Comment by CarnyPriest** [comment]
[batmanf_500.zip](https://github.com/user-attachments/files/17531437/batmanf_500.zip)

Patched set here if you need it.

**Comment by toxieainc** [comment]
..and in, thanks again!  :)
