### ISSUE TITLE
Vpinmame beta hangs on exits

### ISSUE THREAD

**Issue by mazjohn** [vpinball/pinmame#368]
The latest Vpinmame Beta 1152 master build is causing about a 5-10 second hang when exiting tables back into pinup popper.  DOF Matrix seems to also temporarily hang and freeze on Exit... when I switch back to latest beta release 1122 the issue is gone. I tested this in different ways to isolate and the behavior occurs when I use the latest Vpinmame release v 1152 - not sure exactly when this issue begins but its is somewhere after build 1122.

**Comment by JorgePedro65** [comment]
I have the same issue.

**Comment by vbousquet** [comment]
This seems to only happen when using a dmddevice.dll on x64 (at least on my tests). Beside, https://github.com/vpinball/pinmame/issues/369 states that version 1144 was good and there were no changes on that part of the code after this version. DId you update other external components like lucky or Freezy's dmddevice.dll ?

**Comment by mazjohn** [comment]
Thanks. No other external components had been updated prior to reporting this issue (it’s worth noting that all baller installer components are updated and current)….As a next step, I just upgraded to freezy’s latest 2.30 release (and the dmd device.dll was also just updated), so what I can do is try upgrading Vpx beta again above 1122 and retest.. if it happens again I will try to isolate between everything and report back…thank you

**Comment by Dicentim974** [comment]
Hi, same issue here, plus undercab leds continue to work even when the table is closed.
I rolled back to 1122 and the tables are closing the right way (but still the strange Gilligan's Island DOF issue I reported on another topic).

**Comment by studlygoorite** [comment]
I'll note that I was having issues also, falling back to 1144 wasn't enough, I still had a 20 second delay on some tables trying to back out, falling back to v1122 and so far so good.

**Comment by USNCPO** [comment]
Same here. Caused crashing and long delays. Rolled back to 1122 and fixed the issue.

**Comment by vbousquet** [comment]
Fixed by https://github.com/vpinball/pinmame/commit/03144d42ffce5f6cf0cfcb3bdc986d77ce9c4cdf
Thanks for the report!
