### ISSUE TITLE
pinmame scripting?

### ISSUE THREAD

**Issue by huguesbr** [vpinball/pinmame#37]
Hi,

I would like to write a VBS which will allow to mass set some settings of some tables I know the logic of (Bally).
The script will start the rom, trigger the correct sequence of button to change volume or change a settings.

Is it possible?

Can you point me to the right direction? (I'm a dev, but not on windows ^^ -- macOS and iOS ^^)

In a short what's the exposed API from the pinmame com object?

**Comment by freezy** [comment]
Have a look at [`vpinball/pinmame-dotnet`](https://github.com/vpinball/pinmame-dotnet), you should be able to do that pretty easily.

**Comment by huguesbr** [comment]
oh this is great ! @freezy 🙏

**Comment by jsm174** [comment]
@huguesbr  - `pinmame-dotnet` + `libpinmame` are still works in progress, so if you have any suggestions, let us know.

If you look at the Example app, specifically: https://github.com/vpinball/pinmame-dotnet/blob/master/src/PinMame.Example/Example.cs#L194

You'll see how one could script a few keypresses, switches, etc.
