### ISSUE TITLE
REQ: Another code addition from slochar / Idleman (Stern Big Game)

### ISSUE THREAD

**Issue by CarnyPriest** [vpinball/pinmame#370]
Link to one more recent addition:

https://tsqmadness.com/slochar/ZIP/BIGGAME_V13.ZIP

changes from V12:

9)
A factory bug where the following can occur:

[a]	dips are set for 5k/line bonus on ball 3 (or any
ball greater than current ball)

[b] you complete one set of cards and have reserve bonus
lit

[c] you do NOT complete any 'lines' on the second set of
cards

[d] the ball that should light the 5k/line bonus does not
at the start of the ball (this is the bug)

[e] if you drain before completing a line, you do not get
the 5k/line bonus for any set of cards (should always get
it if eligible for the reseved set since all lines are
complete)

**Comment by toxieainc** [comment]
Thanks for the heads up!
