### ISSUE TITLE
Vpinmame timer issue

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/pinmame#379]
Was a B2S issue going back to 2.1.2 seems to have fixed it..
Can B2S cause this even if you dont use a backglass? doing more testing but I put in my old files and slowly updating them to find the problem. So far with my old b2s things seem ok but will do more testing.

Ok been testing this a lot cause we released the newer vpinmame in popper updater and now getting flooded with issues.  Flashers and lights stay lit until the same light is triggered again, flippers stay up or down.  Cannons won't turn or fire. 
Can delete the nvram but soon as you close the table and reopen it's back.
Also I can change the timer in the editor and will fix it for 1 game
Some table pinmame timers on 1 or 10 setting them to -1 helps but still messes up after a few min.
But it has to do something with the timer. 
All tables old and new even the vpw releases. 
Been working on this table and it will play perfect then might load it up and it do this.

https://github.com/user-attachments/assets/2270ecfd-dbea-4a31-a613-739691c3e625

**Comment by toxieainc** [comment]
What was the resolution here?

**Comment by volkenborn** [comment]
Hehe, @Loadedweapon provided the solution by adding it on top by editing his original post. 😀
Check the edit history for details.

**Comment by toxieainc** [comment]
Hmmm.. I blame it on me getting old  ;)

As for B2S being the prob even without backglass: From my understanding, everything is re-routed via/forwarded to B2S if you set it up as default.

**Comment by Loadedweapon** [comment]
Haha no worries toxic I know the feeling.. I was pulling my hair out for a min but finally figured it out. Was very surprised that b2s could even affect the table. Thanks for everything you guys do!
