### ISSUE TITLE
Regression: Fish Tales DMD goes blank while calculating bonuses

### ISSUE THREAD

**Issue by hotelvictorcharlie** [vpinball/pinmame#382]
[This bug](https://github.com/vpinball/pinmame/issues/337) was fixed previously, but I recently upgraded and I am seeing the exact same problem again. Version 3.6.0-1162 is working, but 3.6.0-1163 is broken, therefore it looks like the regression was introduced in [this change](https://github.com/vpinball/pinmame/pull/373).

To reproduce the issue, play Fish Tales and drain a ball. The DMD will go blank for a few seconds while calculating bonuses.

**Comment by volkenborn** [comment]
@vbousquet I had to fix back the sound board type from SNDBRD_DCS to SNDBRD_WPCS.
All Pre-DCS games would crash out when playing the first sound otherwise.

**Comment by vbousquet** [comment]
Sorry for my stupid copy/paste bug... and thanks for fixing!

**Comment by vbousquet** [comment]
@volkenborn shouldn't the memory region be `WPCS_ROMREGION` too ?
