### ISSUE TITLE
No flippers in goldeneye with latest vpinmame build 1180

### ISSUE THREAD

**Issue by mazjohn** [vpinball/pinmame#393]
Flippers not responding at all in goldeneye with latest vpinmame master build 1180. combined with latest vpx x64 build 10.80-2031... Note: when i go back to vpinmame master build 1176 by toxie the issue is gone.

**Comment by GHOSTfaceKILLr1974** [comment]
> Flippers not responding at all in goldeneye with latest vpinmame master build 1180. combined with latest vpx x64 build 10.80-2031... Note: when i go back to vpinmame master build 1176 by toxie the issue is gone.

I have the same issue with Goldeneye. I'm on vpinmame build 1180 and vpx x64 10.8.0 release candidate 6.

**Comment by Dicentim974** [comment]
Hi, unfortunately no Flippers DOF contactors with Capcom tables Breakshot and Street Fighter II.

**Comment by bthitney** [comment]
Noticed no flippers in 1187 x64 with Apollo 13. (I mentioned in other thread but that issue is closed, so mentioning it here.)

**Comment by The1Dijk** [comment]
Can confirm no flippers in Goldeneye on 1182

**Comment by vbousquet** [comment]
Fixed in latest
