### ISSUE TITLE
Flipper issue, Ripley's Believe It or Not (Stern 2004).

### ISSUE THREAD

**Issue by GHOSTfaceKILLr1974** [vpinball/pinmame#398]
Currently on VPX 10.8.0-2044 (x64), VPinMAME 3.6.0.1192 (x64).
Flippers are jumping uncontrollably. If you hold flipper buttons down it sounds like a machine gun is going off!
If this issue was already resolved can you send me a link on how to fix it.
Thank you.

**Comment by jueank** [comment]
Thanks a lot Vicent for taking care of such issues!
You give a lot to the community! :)
