### ISSUE TITLE
libpinmame export symbols list too large

### ISSUE THREAD

**Issue by ciberfred** [vpinball/pinmame#43]
All symboles are exported and only libpinmame_API entries sould be exported.
like on windows. the unix part should replace in src/libpinmame/libpinmame.h : 
#define LIBPINMAME_API extern "C"
by
#define LIBPINMAME_API __attribute__((__visibility__("default")))

and in cmake/libpinmame/CMakeLists_linux-x64.txt
add
set_target_properties(pinmame PROPERTIES COMPILE_FLAGS "-fvisibility=hidden")

with this all functions will be hidden expect the one declared with libpinmame_api in header file.

this will resolve conflict api/abi call with osd_fread function that exist in other lib.

**Comment by jsm174** [comment]
@ciberfred, I'll take a look at this. Thanks!

**Comment by jsm174** [comment]
@ciberfred - can you please try: 

https://github.com/jsm174/pinmame/tree/libpinmame/visibility

or

https://github.com/jsm174/pinmame/actions/runs/916399250

**Comment by ciberfred** [comment]
it works :)

**Comment by jsm174** [comment]
Great. Thanks. Fixed in https://github.com/vpinball/pinmame/pull/44!
