### ISSUE TITLE
How to debug with pinmame ?

### ISSUE THREAD

**Issue by tmator** [vpinball/pinmame#51]
Hi,

i got pinmame to analyse and learn some pinball roms. 

I tried with "Simpsons Data East 2.7" i can read ram but can't launch game, still saying "missing balls". 
Sampe problems with others roms i tried. How can i add some balls rand run game ?

Thanks,

**Comment by tmator** [comment]
Finally i Got it by using matrix switchs but impossible to add a second player, any idea ?

**Comment by toxieainc** [comment]
@volkenborn is the specialist here..

**Comment by vbousquet** [comment]
The user interface in PinMame depends on each rom drivers. Somes don't offer controls, others are pretty complete. For testing you can have a go at Twilight Zone or Creature From The Black Lagoon, they have keyboard shortcuts for all the switches and should let you do complete games and tests.

**Comment by toxieainc** [comment]
Also see https://www.maddes.net/pinball/wpc_debugging.htm
