### ISSUE TITLE
libpinmame ld error

### ISSUE THREAD

**Issue by ciberfred** [vpinball/pinmame#58]
```
[  0%] Linking CXX shared library libpinmame.so
/usr/bin/ld : CMakeFiles/pinmame.dir/src/libpinmame/libpinmame.cpp.o:(.bss+0x10) : définitions multiples de « vector_updates »; CMakeFiles/pinmame.dir/src/vidhrdw/avgdvg.c.o:(.bss+0x0) : défini pour la première fois ici
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pinmame.dir/build.make:4814 : libpinmame.so.3.5] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:124 : CMakeFiles/pinmame.dir/all] Erreur 2
make: *** [Makefile:103 : all] Erreur 2

## grep -R "vector_updates" *
grep: build/CMakeFiles/pinmame.dir/src/mame.c.o: binary file matches
grep: build/CMakeFiles/pinmame.dir/src/vidhrdw/avgdvg.c.o: binary file matches
grep: build/CMakeFiles/pinmame.dir/src/libpinmame/libpinmame.cpp.o: binary file matches

===>
vector_updates variable in src/libpinmame/libpinmame.cpp is already defined in src/mame.c
```
could be renamed or changed to 'static int' to be build correctly on linux.

**Comment by jsm174** [comment]
Hi. I will look into this. I remember I had to add that because it couldn't find `vector_updates` when linking. 

FWIW, if you look at the workflow that compiles libpinmame, we are not having that error:

https://github.com/vpinball/pinmame/actions/runs/2369815830

**Comment by ciberfred** [comment]
well really strange, get debian 11 (gcc 10.2.1) and if i remove this declaration all is works too.

**Comment by jsm174** [comment]
Apologizes for taking so long on this. I removed the `vector_updates` variable in https://github.com/vpinball/pinmame/pull/59. This issues should now be fixed.
