### ISSUE TITLE
Modulated solenoids in SE hardware

### ISSUE THREAD

**Issue by apophis79** [vpinball/pinmame#66]
Currently pinmame does not support modulated solenoid outputs in Stern/SEGA Whitestar (SE) machines, despite those machines having this capability. It would be great to be able to use modulated signals with these machines.

**Comment by vbousquet** [comment]
PR #91 adds PWM integration which is a similar feature to modulated solenoids, giving user more control on the way the modulation is computed. So SE hardware do have modulated outputs now.

@toxieainc I think this can be closed for now. @apophis79 please reopen it if the new feature does not fully cover this request.

**Comment by toxieainc** [comment]
Thanks!
