### ISSUE TITLE
im186ve FastFlip Enable Request

### ISSUE THREAD

**Issue by Sixtoe** [vpinball/pinmame#76]
Can someone please add Iron Man Vault Edition ROM im186ve FastFlip support please?

**Comment by toxieainc** [comment]
@djrobx was the specialist for these kinds of things

**Comment by djrobx** [comment]
There's a long comment in the code that describes how to do it.   Requires visual studio debugger and CheatEngine.

**Comment by toxieainc** [comment]
Done via https://github.com/vpinball/pinmame/commit/d5c04c39b6a3b051a45bbaa8df624620bc012b1d
