### ISSUE TITLE
VPinMAME 64 bit Tables with Altsound 2 did not start

### ISSUE THREAD

**Issue by Ahriman0** [vpinball/pinmame#81]
VPinMAME 64 bit Tables with Altsound 2 did not start, if you turn Altsound to 1 or 0 there is no Problem

**Comment by toxieainc** [comment]
Is there actually a Pinsound Studio 64bit version?
Otherwise Altsound 2 will only work with the 32bit version.

**Comment by toxieainc** [comment]
As no more feedback, closing
