### ISSUE TITLE
Gottlieb System 3: Flashers not correct

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/pinmame#97]
![Flashers](https://user-images.githubusercontent.com/81928693/217435432-70906bf0-2acd-4159-9ff6-b7d2d6db7dfd.jpg)
![Flashers](https://user-images.githubusercontent.com/81928693/217435475-adf3617d-ff22-4173-9bd8-17eb164aae7f.jpg)

**Comment by JorgePedro65** [comment]
The game worked perfectly before. If I turn solenoids off, the game does not work.

**Comment by JorgePedro65** [comment]
The flashers are too bright now.

**Comment by volkenborn** [comment]
@JorgePedro65 What flashers are you referring to?
The ramp flashers are driven by the aux driver (Lamps 120..127).
In what way are they "too bright"? I'm assuming they are on when they shouldn't be?
In which previous version did it work differently?

**Comment by JorgePedro65** [comment]
[VPinballX-10.8.0-635-63b095e-Release-win-x86](https://github.com/vpinball/vpinball/suites/9933993097/artifacts/480822496)
This is the latest one that works for me.

**Comment by toxieainc** [comment]
So this rather sounds like a VPX problem then. Could you please file this issue under https://github.com/vpinball/vpinball ?

**Comment by toxieainc** [comment]
Thanks!
