### ISSUE TITLE
BUG: Big Game (Stern 1980) - sound bug (blurp)

### ISSUE THREAD

**Issue by redbone75** [vpinball/pinmame#98]
Big Game (Stern 1980) - https://www.vpforums.org/index.php?app=downloads&showfile=12920

After game starts and ball drops, every 3-4 seconds there is a constant "blurp" coming from the sound.

I've recorded a video/audio to demonstrate - https://www.youtube.com/watch?v=orTv2PsePJA

After talking to JP, he said it was an emulation problem and nothing with the table.

**Comment by volkenborn** [comment]
Did you read the comments about how to turn off the "background noise", whatever it is?

https://www.vpforums.org/index.php?app=downloads&showfile=12920&st=20#commentsStart

**Comment by volkenborn** [comment]
Also note that DIP switch #8 needs to be in the ON position to turn off that sound.
Closed because it's a config option, and correct behaviour.

**Comment by redbone75** [comment]
Amazing.  Thank you @volkenborn !  

F6 and Set "Background sound" to ON fixes the issue I was reporting.
![BG-redbone-mod-screenshot-blurp-fix](https://user-images.githubusercontent.com/20893831/218791957-2721c2a0-0f55-4226-816f-f5e232b0985f.jpg)

**Comment by redbone75** [comment]
I tested  Mod rev 9 and looks like the "blurp" persists regardless of the background sound dip switch setting.

https://vpuniverse.com/files/file/7569-big-game-mod-rev-9/

**Comment by volkenborn** [comment]
@redbone75 That's an issue with the biggamed ROM itself, not PinMAME.
The (inverted) DIP switch #8 works on the original biggame set.
I posted CarnyPriest about this, maybe they'll release a version 10...

**Comment by volkenborn** [comment]
Scott Charles, the mod author, wrote:

> "the early mpu200 sound engine does strange things with the background sound if the nvram doesn't have 'something' in there from a previous boot.  Did not realize that big game has it (meteor and galaxy verified to have this, and ali probably does as well but not personally verified).  That is likely the cause of the humming, especially if it goes away after it gets initialized.

So I just tested this in my game, the background sound stops after the first regular sound plays.  I don't know if the original does that or not.  I think at the time stern was thinking most people would not turn off the sound anyway but I suppose after meteor not being able to turn off the sound they got complaints (most of the meteor sound effects assume you're going back to the background so the sounds would all have to be edited to turn that off)

I'll take a look at some point to see why it's still starting the BG when it's 'off' probably just a missed flag check/wrong state, but it's not going to be quick I don't currently have the time to invest in projects right now beyond cursory looks."

**Comment by volkenborn** [comment]
[BIGGAME_V12.ZIP](https://github.com/vpinball/pinmame/files/13762830/BIGGAME_V12.ZIP)

Here's a new MOD version that will cure the issue.
