### ISSUE TITLE
Add STTNG_LX8

### ISSUE THREAD

**Issue by BRoadifer** [vpinball/pinmame#99]
https://drive.proton.me/urls/WZV79221ZC

**Comment by BRoadifer** [comment]
I guess this is already done...

Exactly 29 years after the release of LX-7 - which came out on Feb. 17 1994 - I'm really proud – and a little surprised - to announce the release of something really cool:
More than 20 bugs fixed.
Features! Tweaks! Improvements!
For sure the No 1. upgrade every STTNG should have installed.
And it simply plays fantastic!
The goal was to eliminate bugs and inconsistencies, but also to add obviously missing features. Everything was designed to maintain the spirit of the original game and every change that is not a bug-fix can be disabled. But if you like LX-7 you are certainly going to love LX-8.
If you own a legal copy of LX-7, here you are going to find everything you need - including a well written manual with 22 fine pages answering everything you might want to know:
[https://drive.proton.me/urls/WZV79221ZC#SFQiTtAwWYm2](https://drive.proton.me/urls/WZV79221ZC?fbclid=IwAR1kChG-2ZuOkfu-j2MrJoXDYVwaO6kAM940uoYeGSk5Z4zfed1YZyv_8JA#SFQiTtAwWYm2)
For sure a serious amount of time went into developing, testing and documenting all of this. Over at flippermarkt.de a very competent alliance of fellow STTNG owners teamed up to make this happen!
For your thoughts, ideas, extensive testing, bug reports, continuous and persistent help to make one of the best pinball machines of all time even better, special thanks (and shouts!!) go out to:
Guitarluke - oradke - grabul - agolo - chessman68 - mineu - Thargor - rocanich – ClarkKent
And for additional beta testing:
toxie - koji - Manny65 - Eric_Manuel

**Comment by toxieainc** [comment]
Yup, already done: https://github.com/vpinball/pinmame/commit/9423657f2470f549934710860f58abfa51c0b042
